/**
 * @NApiVersion 2.1
 * @NModuleScope SameAccount
 *
 * Planif Arbitrage (Suitelet) - rendu HTML/CSS/JS.
 * Renvoie le balisage complet de l'écran (CSS + JS client embarqués, pas de
 * N/ui/serverWidget - Annexe B.1). Modelé sur wo_tree_html.js : le GET du
 * Suitelet rend cette page une fois, toute interaction ensuite passe par
 * fetch() vers le même Suitelet (routeur JSON POST).
 *
 * Système de design repris de la maquette validée (Annexe A) : la couleur
 * encode QUI a décidé (planificateur vs moteur), jamais la gravité.
 * Police : pile système par défaut (Annexe A.3 interdit une dépendance à un
 * CDN de polices depuis un Suitelet) - l'auto-hébergement des fichiers
 * woff2 depuis le File Cabinet est une passe ultérieure, non bloquante pour
 * cette version.
 */
define([], function () {

    var PA_VERSION = '1.0.0';

    // Échappe un objet pour une injection sûre dans un <script> inline -
    // sans ça, un nom d'article ou d'emplacement contenant "</script>"
    // casserait le HTML généré.
    function safeScriptJson(obj) {
        return JSON.stringify(obj || null)
            .replace(/</g, '\\u003c')
            .replace(/>/g, '\\u003e')
            .replace(/\u2028/g, '\\u2028')
            .replace(/\u2029/g, '\\u2029');
    }

    function renderPage(ctx) {
        var suiteletUrl = ctx.suiteletUrl || '';

        return [
'<!DOCTYPE html>',
'<html lang="fr">',
'<head>',
'<meta charset="UTF-8">',
'<meta name="viewport" content="width=device-width, initial-scale=1">',
'<title>Séquencement et fractionnement des ordres planifiés</title>',
'<style>', baseCss(), '</style>',
'</head>',
'<body>',
'<div class="pa-app">',

'  <div class="pa-topbar">',
'    <div>',
'      <div class="pa-crumb">Fabrication &nbsp;›&nbsp; Planification</div>',
'      <h1>Séquencement des ordres planifiés</h1>',
'    </div>',
'    <span class="pa-version">v' + PA_VERSION + '</span>',
'    <a class="pa-back" href="/app/center/card.nl" title="Retour à NetSuite">← Retour à NetSuite</a>',
'  </div>',

'  <div class="pa-wrap">',

'    <dl class="pa-planbar">',
'      <div class="pa-pb"><dt>Plan d’approvisionnement</dt><dd><select id="pa-planSelect" class="mono"></select></dd></div>',
'      <div class="pa-pb"><dt>Dernier calcul</dt><dd id="pa-lastRun" class="mono">—</dd></div>',
'      <div class="pa-pb"><dt>Arbitrages en attente</dt><dd id="pa-basket">—</dd></div>',
'      <div class="pa-pb"><dt>Niveaux à arbitrer</dt><dd id="pa-levelsTodo" class="mono">—</dd></div>',
'      <div class="pa-grow">',
'        <button class="pa-btn-ghost" id="pa-btnRefresh">Actualiser</button>',
'      </div>',
'    </dl>',

'    <div class="pa-picker">',
'      <div class="pa-combo">',
'        <label for="pa-artInput">Article à planifier</label>',
'        <div class="pa-combo-row">',
'          <input id="pa-artInput" type="text" role="combobox" aria-expanded="false" aria-controls="pa-artList"',
'                 aria-autocomplete="list" autocomplete="off" placeholder="Code ou désignation…">',
'          <button class="pa-combo-toggle" id="pa-artToggle" aria-label="Afficher la liste des articles">▼</button>',
'        </div>',
'        <ul id="pa-artList" role="listbox" hidden></ul>',
'      </div>',
'      <span class="pa-picker-hint" id="pa-pickerHint"></span>',
'    </div>',

'    <div class="pa-blank" id="pa-blank">',
'      <h3>Choisissez un article pour commencer</h3>',
'      <p>Le premier chiffre du code donne le niveau de nomenclature.<br>',
'         Traitez un niveau complet, puis relancez le calcul.</p>',
'    </div>',

'    <div id="pa-content" hidden>',
'      <dl class="pa-context">',
'        <div class="pa-ctx"><dt>Article</dt><dd id="pa-cArt">—</dd></div>',
'        <div class="pa-ctx"><dt>Temps TERM</dt><dd id="pa-cTempsTerm">—</dd></div>',
'        <div class="pa-ctx"><dt>Temps VAC</dt><dd id="pa-cTempsVac">—</dd></div>',
'        <div class="pa-ctx"><dt>Emplacement</dt><dd id="pa-cLoc">—</dd></div>',
'      </dl>',

'      <div class="pa-legend">',
'        <div class="pa-lg-human">',
'          <strong>Décidé par le planificateur</strong>',
'          <span>Quantités et dates saisies ici. Firmées : le calcul ne les modifie plus.</span>',
'        </div>',
'        <div class="pa-lg-engine">',
'          <strong>Calculé par le moteur</strong>',
'          <span>Propositions issues du niveau supérieur, de la nomenclature et des délais.</span>',
'        </div>',
'      </div>',

'      <section>',
'        <div class="pa-sec-head"><h2>Propositions de l’article</h2><span class="pa-spec">F1 · F2</span></div>',
'        <div class="pa-week-filter">',
'          <label for="pa-weekFilter">Semaine</label>',
'          <select id="pa-weekFilter"><option value="">Toutes les semaines</option></select>',
'        </div>',
'        <table>',
'          <thead><tr>',
'            <th style="width:34px"></th><th class="num" style="width:100px">Quantité</th>',
'            <th style="width:110px">Début</th><th style="width:110px">Fin</th>',
'            <th style="width:110px">Origine</th>',
'          </tr></thead>',
'          <tbody id="pa-rows"></tbody>',
'        </table>',
'        <div class="pa-note" id="pa-buyNote" hidden>',
'          Article acheté : la proposition est un ordre d’achat. La répartition se négocie avec',
'          le fournisseur, elle n’est pas traitée par cet écran.',
'        </div>',

'        <div class="pa-split" id="pa-splitPanel" hidden>',
'          <div class="pa-split-in">',
'            <p class="pa-split-title">Répartir la quantité</p>',
'            <div class="pa-fields">',
'              <div class="pa-f"><label for="pa-mode">Méthode</label>',
'                <select id="pa-mode" style="width:170px">',
'                  <option value="perday">Quantité par jour</option>',
'                  <option value="lots">Nombre de lots</option>',
'                  <option value="free">Saisie libre</option>',
'                </select></div>',
'              <div class="pa-f" id="pa-fQty"><label id="pa-lblQty" for="pa-qtyDay">Quantité / jour</label>',
'                <input id="pa-qtyDay" class="mono" type="number" value="1" min="0" step="any"></div>',
'              <div class="pa-f pa-f-wide" id="pa-fFirst"><label for="pa-firstDay">Premier jour</label>',
'                <input id="pa-firstDay" class="mono" type="date"></div>',
'              <div class="pa-f" id="pa-fWork"><label class="pa-check" style="margin-bottom:6px">',
'                <input type="checkbox" id="pa-workdays" checked> Jours ouvrés seulement</label></div>',
'              <button class="pa-btn-ghost" id="pa-btnPreview">Proposer une répartition</button>',
'            </div>',
'            <div class="pa-preview" id="pa-preview" hidden>',
'              <div class="pa-preview-h">Répartition — chaque ligne est modifiable</div>',
'              <table class="pa-lines"><thead><tr>',
'                <th style="width:150px">Date</th><th>Article</th><th style="width:120px">Quantité</th>',
'                <th style="width:70px">Lancer</th><th>Observation</th><th style="width:40px"></th>',
'              </tr></thead><tbody id="pa-lineBody"></tbody></table>',
'              <button class="pa-btn-link" id="pa-btnAddLine">+ Ajouter une ligne</button>',
'              <div class="pa-total" id="pa-total"></div>',
'              <div style="margin-top:13px">',
'                <button class="pa-btn-primary" id="pa-btnApply">Appliquer et firmer</button>',
'                <button class="pa-btn-link" id="pa-btnCancel">Annuler</button>',
'              </div>',
'            </div>',
'          </div>',
'        </div>',
'      </section>',

'      <section class="pa-quiet">',
'        <div class="pa-sec-head pa-sec-sub">',
'          <button class="pa-toggle" type="button" data-target="pa-comps-wrap" aria-expanded="true" aria-label="Réduire le tableau des composants">▾</button>',
'          <h2>Composants — pour information</h2><span class="pa-spec">F8</span>',
'        </div>',
'        <div id="pa-comps-wrap">',
'        <table>',
'          <thead><tr>',
'            <th style="width:70px">Niveau</th><th>Article</th>',
'            <th class="num" style="width:100px">Quantité</th>',
'            <th style="width:110px">Début</th><th style="width:110px">Fin</th>',
'            <th style="width:110px">Origine</th>',
'          </tr></thead>',
'          <tbody id="pa-comps"></tbody>',
'        </table>',
'        <p class="pa-stamp" id="pa-compStamp"></p>',
'        </div>',
'      </section>',

'      <section class="pa-quiet">',
'        <div class="pa-sec-head pa-sec-sub">',
'          <button class="pa-toggle" type="button" data-target="pa-grandcomps-wrap" aria-expanded="true" aria-label="Réduire le tableau des composants des composants">▾</button>',
'          <h2>Composants des composants — pour information</h2>',
'        </div>',
'        <div id="pa-grandcomps-wrap">',
'        <table>',
'          <thead><tr>',
'            <th style="width:70px">Niveau</th><th>Article</th><th>Composant parent</th>',
'            <th class="num" style="width:100px">Quantité</th>',
'            <th style="width:110px">Début</th><th style="width:110px">Fin</th>',
'            <th style="width:110px">Origine</th>',
'          </tr></thead>',
'          <tbody id="pa-grandcomps"></tbody>',
'        </table>',
'        <p class="pa-stamp">Un niveau supplémentaire d’information, sous le même principe que les composants directs : jamais modifiable ici.</p>',
'        </div>',
'      </section>',

'      <section>',
'        <div class="pa-sec-head"><h2>Journal des interventions</h2><span class="pa-spec">F9</span></div>',
'        <table>',
'          <thead><tr><th style="width:150px">Horodatage</th><th style="width:140px">Utilisateur</th>',
'            <th>Opération</th></tr></thead>',
'          <tbody id="pa-journal"></tbody>',
'        </table>',
'        <p class="pa-stamp" id="pa-journalEmpty">Aucune intervention.</p>',
'      </section>',
'    </div>',
'  </div>',

'  <div id="pa-toast" class="pa-toast"></div>',
'</div>',

'<script>',
'  window.PA_URL = ' + safeScriptJson(suiteletUrl) + ';',
'</script>',
'<script>', baseJs(), '</script>',
'</body>',
'</html>'
        ].join('\n');
    }

    function baseCss() {
        return [
            // Jetons de couleur repris de la maquette (Annexe A.2) - la
            // couleur encode QUI a décidé, jamais la gravité (Annexe A.1).
            ':root{--slate:#44597a;--slate-dk:#33445d;--ns-blue:#1f6fd0;--ns-blue-dk:#175aad;',
            '--human:#b1701a;--human-bg:#fdf6e9;--human-br:#e3c9a0;',
            '--engine:#0f6e6e;--engine-bg:#eef6f6;--engine-br:#b8d6d6;',
            '--alert:#a8322d;--alert-bg:#fbeceb;',
            '--ink:#1c2430;--ink-2:#5a6675;--ink-3:#8a95a3;--rule:#d7dce3;--rule-lt:#e8ecf1}',
            '*{box-sizing:border-box}',
            'html,body{margin:0;padding:0}',
            // Pile système par défaut - pas de CDN de polices depuis un
            // Suitelet (Annexe A.3). L'auto-hébergement woff2 depuis le
            // File Cabinet est une passe ultérieure.
            'body{font-family:-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;font-size:13px;color:var(--ink);background:#eaedf1;line-height:1.45}',
            '.mono{font-family:ui-monospace,Menlo,Consolas,monospace;font-variant-numeric:tabular-nums}',
            '.pa-topbar{background:var(--slate);color:#fff;padding:10px 20px;display:flex;align-items:center;gap:16px;flex-wrap:wrap}',
            '.pa-topbar h1{font-size:15px;font-weight:600;margin:0}',
            '.pa-crumb{font-size:11px;color:#c3cddd;text-transform:uppercase;letter-spacing:.09em}',
            '.pa-version{font-family:ui-monospace,monospace;font-size:11px;background:rgba(255,255,255,.15);border-radius:3px;padding:2px 8px}',
            '.pa-back{margin-left:auto;color:#fff;font-size:12px;text-decoration:none;opacity:.9}',
            '.pa-back:hover{text-decoration:underline}',
            '.pa-wrap{max-width:1180px;margin:0 auto;padding:18px 20px 60px}',
            '.pa-planbar{background:#fff;border:1px solid var(--rule);border-left:4px solid var(--slate);padding:12px 16px;display:flex;align-items:center;gap:22px;flex-wrap:wrap;margin-bottom:14px}',
            '.pa-pb{display:flex;flex-direction:column;gap:2px}',
            '.pa-pb dt{font-size:10px;text-transform:uppercase;letter-spacing:.08em;color:var(--ink-3)}',
            '.pa-pb dd{margin:0;font-size:13px;font-weight:500}',
            '.pa-pb dd.warn{color:var(--human);font-weight:600}',
            '#pa-planSelect{font-size:13px;padding:4px 7px;border:1px solid #b6c0cd;border-radius:2px;background:#fff;max-width:260px}',
            '.pa-planbar .pa-grow{margin-left:auto;display:flex;gap:9px;align-items:center}',
            '.pa-picker{background:#fff;border:1px solid var(--rule);padding:14px 16px;display:flex;align-items:flex-end;gap:16px;flex-wrap:wrap;margin-bottom:14px}',
            '.pa-picker label{display:block;font-size:10.5px;text-transform:uppercase;letter-spacing:.08em;color:var(--ink-2);margin-bottom:5px}',
            '.pa-combo{position:relative}',
            '.pa-combo-row{display:flex}',
            '.pa-combo input{font-size:13px;padding:6px 9px;width:320px;border:1px solid #b6c0cd;border-right:0;border-radius:2px 0 0 2px}',
            '.pa-combo-toggle{border:1px solid #b6c0cd;background:#f0f3f7;border-radius:0 2px 2px 0;padding:0 11px;cursor:pointer;font-size:11px;color:var(--ink-2)}',
            '.pa-combo-toggle:hover{background:#e5eaf1}',
            '.pa-combo ul{position:absolute;z-index:30;top:calc(100% + 3px);left:0;width:470px;margin:0;padding:0;list-style:none;background:#fff;border:1px solid #9aa7b8;box-shadow:0 6px 18px rgba(28,36,48,.16);max-height:340px;overflow:auto}',
            '.pa-combo li.grp{padding:7px 12px 5px;background:#eef1f5;border-top:1px solid var(--rule-lt);font-size:10px;text-transform:uppercase;letter-spacing:.08em;color:#41505f;font-weight:700;position:sticky;top:0}',
            '.pa-combo li.opt{padding:7px 12px;cursor:pointer;display:flex;align-items:center;gap:10px;border-left:3px solid transparent}',
            '.pa-combo li.opt:hover,.pa-combo li.opt.cursor{background:#eaf2fd;border-left-color:var(--ns-blue)}',
            '.pa-combo li.opt .code{font-family:ui-monospace,monospace;font-size:12.5px;color:var(--ink-2);width:64px;flex:0 0 64px}',
            '.pa-combo li.opt .nm{flex:1}',
            '.pa-combo li.opt .nm em{display:block;font-style:normal;font-size:11px;color:var(--ink-3)}',
            '.pa-combo li.none{padding:10px 12px;color:var(--ink-3);font-style:italic}',
            '.pa-badge{font-size:10px;font-weight:600;letter-spacing:.05em;text-transform:uppercase;padding:2px 6px;border-radius:2px;white-space:nowrap}',
            '.pa-badge-todo{background:var(--engine-bg);color:var(--engine);border:1px solid var(--engine-br)}',
            '.pa-badge-done{background:var(--human-bg);color:var(--human);border:1px solid var(--human-br)}',
            '.pa-badge-buy{background:#f0f2f5;color:var(--ink-2);border:1px solid var(--rule)}',
            '.pa-picker-hint{font-size:11.5px;color:var(--ink-2);padding-bottom:6px}',
            '.pa-context{display:grid;grid-template-columns:repeat(auto-fit,minmax(140px,1fr));gap:1px;background:var(--rule);border:1px solid var(--rule)}',
            '.pa-ctx{background:#fff;padding:9px 13px}',
            '.pa-ctx dt{font-size:10px;text-transform:uppercase;letter-spacing:.08em;color:var(--ink-3);margin:0 0 3px}',
            '.pa-ctx dd{margin:0;font-size:13px;font-weight:500}',
            '.pa-blank{background:#fff;border:1px solid var(--rule);padding:44px 24px;text-align:center}',
            '.pa-blank h3{margin:0 0 6px;font-size:14px;font-weight:600}',
            '.pa-blank p{margin:0;font-size:12.5px;color:var(--ink-2)}',
            '.pa-week-filter{background:#fff;border:1px solid var(--rule);border-top:0;border-bottom:0;padding:9px 13px;display:flex;align-items:center;gap:9px}',
            '.pa-week-filter label{font-size:10.5px;text-transform:uppercase;letter-spacing:.08em;color:var(--ink-2)}',
            '.pa-week-filter select{font-family:ui-monospace,monospace;font-size:12.5px;padding:5px 8px;border:1px solid #b6c0cd;border-radius:2px;background:#fff;min-width:220px}',
            '.pa-legend{display:flex;margin:14px 0 20px;border:1px solid var(--rule);background:#fff}',
            '.pa-legend>div{flex:1;padding:11px 14px;border-left:4px solid}',
            '.pa-legend>div+div{box-shadow:inset 1px 0 0 var(--rule-lt)}',
            '.pa-lg-human{border-left-color:var(--human)}',
            '.pa-lg-engine{border-left-color:var(--engine)}',
            '.pa-legend strong{display:block;font-size:12px}',
            '.pa-legend span{font-size:11.5px;color:var(--ink-2)}',
            'section{margin-bottom:22px}',
            '.pa-sec-head{display:flex;align-items:baseline;gap:12px;padding:0 0 7px;border-bottom:2px solid var(--slate)}',
            '.pa-toggle{background:none;border:1px solid var(--rule);border-radius:2px;color:var(--ink-2);width:22px;height:22px;padding:0;line-height:1;font-size:11px;display:inline-flex;align-items:center;justify-content:center}',
            '.pa-toggle:hover{background:var(--rule-lt)}',
            '.pa-toggle[aria-expanded="false"]{transform:rotate(-90deg)}',
            '.pa-sec-head h2{font-size:13px;font-weight:600;margin:0;text-transform:uppercase;letter-spacing:.07em}',
            '.pa-sec-head .pa-spec{font-size:10.5px;color:var(--ink-3);margin-left:auto}',
            '.pa-sec-sub{border-bottom-width:1px;border-bottom-color:var(--rule)}',
            '.pa-sec-sub h2{color:var(--ink-2);font-size:12px}',
            'table{width:100%;border-collapse:collapse;background:#fff;border:1px solid var(--rule);border-top:0}',
            'thead th{background:#dfe4ea;font-size:10.5px;text-transform:uppercase;letter-spacing:.07em;color:#41505f;text-align:left;padding:7px 10px;font-weight:600;white-space:nowrap}',
            'tbody td{padding:8px 10px;border-top:1px solid var(--rule-lt);vertical-align:middle}',
            'tbody tr.pa-sel{background:#eaf2fd}',
            'tbody tr.pa-is-human{box-shadow:inset 4px 0 0 var(--human)}',
            'tbody tr.pa-is-engine{box-shadow:inset 4px 0 0 var(--engine)}',
            'td.num{text-align:right}',
            '.pa-pill{display:inline-block;font-size:10px;font-weight:600;letter-spacing:.06em;text-transform:uppercase;padding:2px 7px;border-radius:2px}',
            '.pa-pill-human{background:var(--human-bg);color:var(--human);border:1px solid var(--human-br)}',
            '.pa-pill-engine{background:var(--engine-bg);color:var(--engine);border:1px solid var(--engine-br)}',
            '.pa-quiet table{background:#fbfcfd}',
            '.pa-quiet thead th{background:#eef1f5;color:#66717f}',
            '.pa-quiet tbody td{color:var(--ink-2)}',
            '.pa-stamp{font-size:11.5px;color:var(--ink-3);padding:7px 0 0}',
            'button{font-family:inherit;font-size:12.5px;cursor:pointer;border-radius:2px;padding:6px 14px;border:1px solid transparent}',
            '.pa-btn-primary{background:var(--ns-blue);color:#fff;font-weight:500}',
            '.pa-btn-primary:hover{background:var(--ns-blue-dk)}',
            '.pa-btn-primary:disabled{background:#a9bcd4;cursor:not-allowed}',
            '.pa-btn-ghost{background:#fff;border-color:#adb8c6;color:var(--ink)}',
            '.pa-btn-ghost:hover{background:#f0f3f7}',
            '.pa-btn-link{background:none;border:0;color:var(--ns-blue);padding:2px 4px;text-decoration:underline;font-size:12px}',
            ':focus-visible{outline:2px solid var(--ns-blue);outline-offset:1px}',
            '.pa-split{background:#fff;border:1px solid var(--rule);border-top:0}',
            '.pa-split-in{padding:15px 16px;background:var(--human-bg);border-top:1px solid #ecd9b8}',
            '.pa-split-title{font-size:11px;text-transform:uppercase;letter-spacing:.08em;color:var(--human);font-weight:700;margin:0 0 12px}',
            '.pa-fields{display:flex;gap:18px;flex-wrap:wrap;align-items:flex-end}',
            '.pa-f label{display:block;font-size:10.5px;text-transform:uppercase;letter-spacing:.07em;color:var(--ink-2);margin-bottom:4px}',
            '.pa-f input,.pa-f select{font-family:ui-monospace,monospace;font-size:13px;padding:5px 8px;border:1px solid #b6c0cd;border-radius:2px;background:#fff;width:130px}',
            '.pa-f-wide input{width:160px}',
            '.pa-check{display:flex;align-items:center;gap:6px;font-size:12px;color:var(--ink-2)}',
            '.pa-preview{margin-top:14px;border-top:1px dashed #ddc8a4;padding-top:12px}',
            '.pa-preview-h{font-size:10.5px;text-transform:uppercase;letter-spacing:.07em;color:var(--ink-2);margin-bottom:7px}',
            'table.pa-lines{border:1px solid var(--human-br);background:#fff}',
            'table.pa-lines thead th{background:#f6ebd6;color:#7d5210;border:0}',
            'table.pa-lines tbody td{border-top:1px solid #f0e2c8;padding:5px 8px}',
            'table.pa-lines input{font-family:ui-monospace,monospace;font-size:12.5px;padding:4px 7px;border:1px solid #cfd7e1;border-radius:2px;width:100%;background:#fff}',
            'table.pa-lines input.bad{border-color:var(--alert);background:#fef7f6}',
            '.pa-obs{font-size:11.5px;color:var(--ink-3)}',
            '.pa-obs.warn{color:var(--human);font-weight:500}',
            '.pa-obs.err{color:var(--alert);font-weight:500}',
            '.pa-del{background:none;border:0;color:var(--ink-3);cursor:pointer;font-size:14px;padding:2px 6px;line-height:1}',
            '.pa-del:hover{color:var(--alert)}',
            '.pa-flag{margin-top:11px;padding:9px 12px;font-size:12px;border-left:4px solid}',
            '.pa-flag-info{background:var(--engine-bg);border-left-color:var(--engine);color:#0c5757}',
            '.pa-flag-over{background:var(--alert-bg);border-left-color:var(--alert);color:#7d2a26}',
            '.pa-total{margin-top:11px;font-size:12.5px;display:flex;align-items:center;gap:8px;flex-wrap:wrap}',
            '.pa-ok{color:#1d6b3f;font-weight:600}',
            '.pa-note{background:#f4f6f9;border:1px solid var(--rule);border-top:0;padding:11px 15px;font-size:12px;color:var(--ink-2)}',
            '.pa-empty{color:#8a95a3;font-style:italic}',
            '.pa-toast{position:fixed;bottom:22px;right:22px;background:var(--ink);color:#fff;padding:12px 16px;border-radius:6px;opacity:0;transform:translateY(6px);pointer-events:none;transition:opacity .2s,transform .2s;z-index:9999;max-width:420px;font-size:13px;box-shadow:0 10px 28px rgba(0,0,0,.24);border-left:3px solid var(--ns-blue)}',
            '.pa-toast.show{opacity:1;transform:translateY(0);pointer-events:auto}',
            '.pa-toast.error{background:var(--alert);border-left-color:#7a221d}',
            '.pa-toast.success{background:#1d6b3f;border-left-color:#0f4a29}',
            '.pa-toast.warning{background:var(--human);border-left-color:#7d5210}',
            '@media (prefers-reduced-motion: reduce){*,*::before,*::after{transition:none!important}}'
        ].join('\n');
    }

    function baseJs() {
        return [
'(function(){',
'"use strict";',
'var URL = window.PA_URL || "";',
'var state = { levels:[], levelsById:{}, current:null, orders:[], components:[], grandchildComponents:[], selected:null, proposal:null, cursor:-1, selectedPlanId:null, weekFilter:"" };',
'',
'/* Un compte peut porter plusieurs Supply Plan Definition - le plan choisi',
'   est joint à chaque appel serveur (aucune règle métier côté client, juste',
'   un identifiant transporté). */',
'function planPayload(){ return { supplyPlanDefinitionId: state.selectedPlanId }; }',
'',
'function $(sel, ctx){ return (ctx||document).querySelector(sel); }',
'',
'function toast(msg, type, ms){',
'  var el = $("#pa-toast");',
'  el.textContent = msg;',
'  el.className = "pa-toast show " + (type||"");',
'  setTimeout(function(){ el.className = "pa-toast"; }, ms||6000);',
'}',
'',
'/* Plier/déplier un tableau depuis le bouton de son en-tête - affichage',
'   uniquement, aucune donnée ni règle métier. */',
'Array.prototype.slice.call(document.querySelectorAll(".pa-toggle")).forEach(function(btn){',
'  btn.addEventListener("click", function(){',
'    var target = document.getElementById(btn.dataset.target);',
'    if (!target) return;',
'    var expanded = btn.getAttribute("aria-expanded") !== "false";',
'    target.hidden = expanded;',
'    btn.setAttribute("aria-expanded", String(!expanded));',
'  });',
'});',
'',
'function api(action, payload){',
'  return fetch(URL, {',
'    method: "POST",',
'    headers: { "Content-Type": "application/json" },',
'    body: JSON.stringify({ action: action, payload: payload||{} })',
'  }).then(function(r){',
'    return r.text().then(function(txt){',
'      var j = null;',
'      try { j = txt ? JSON.parse(txt) : {}; }',
'      catch(e){ throw new Error("Réponse non-JSON (HTTP " + r.status + ")."); }',
'      if (!r.ok || j.error) throw new Error(j.error || ("HTTP " + r.status));',
'      return j;',
'    });',
'  });',
'}',
'',
'/* ---------------- plan d’approvisionnement ---------------- */',
'function loadSupplyPlans(){',
'  return api("listSupplyPlans", {}).then(function(res){',
'    var sel = $("#pa-planSelect");',
'    sel.innerHTML = "";',
'    (res.plans || []).forEach(function(p){',
'      var opt = document.createElement("option");',
'      opt.value = p.id; opt.textContent = p.name;',
'      sel.appendChild(opt);',
'    });',
'    state.selectedPlanId = res.defaultId && (res.plans||[]).some(function(p){ return p.id === res.defaultId; })',
'      ? res.defaultId : (res.plans && res.plans[0] ? res.plans[0].id : null);',
'    sel.value = state.selectedPlanId;',
'  }).catch(function(err){ toast("Échec du chargement des plans : " + err.message, "error", 9000); });',
'}',
'$("#pa-planSelect").addEventListener("change", function(){',
'  state.selectedPlanId = this.value;',
'  $("#pa-blank").hidden = false; $("#pa-content").hidden = true;',
'  input.value = ""; state.current = null;',
'  refreshPlanBar();',
'});',
'',
'/* ---------------- barre d’état (F4, F5, F6) ---------------- */',
'function refreshPlanBar(){',
'  return api("listItems", planPayload()).then(function(res){',
'    state.levels = res.levels || [];',
'    state.levelsById = {};',
'    state.levels.forEach(function(lvl){',
'      lvl.items.forEach(function(it){ state.levelsById[it.itemId + "|" + it.locationId] = it; });',
'    });',
'    $("#pa-lastRun").textContent = res.lastRun && res.lastRun.runId ? "Run " + res.lastRun.runId : "aucun calcul connu";',
'    var n = res.arbitratedSinceRun || 0;',
'    var b = $("#pa-basket");',
'    b.textContent = n ? (n + (n>1 ? " articles arbitrés" : " article arbitré")) : "Aucun";',
'    b.className = n ? "warn" : "";',
'    $("#pa-levelsTodo").textContent = (res.levelsTodo && res.levelsTodo.length) ? res.levelsTodo.join(" · ") : "aucun";',
'    renderList("");',
'  }).catch(function(err){ toast("Échec du chargement : " + err.message, "error", 9000); });',
'}',
'',
'/* ---------------- sélecteur F1 ---------------- */',
'var input = $("#pa-artInput"), list = $("#pa-artList");',
'',
'function renderList(filter){',
'  var q = (filter||"").toLowerCase();',
'  list.innerHTML = "";',
'  var any = false;',
'  state.levels.forEach(function(lvl){',
'    var hits = lvl.items.filter(function(it){',
'      return !q || (it.code + " " + it.name + " " + it.location).toLowerCase().indexOf(q) > -1;',
'    });',
'    if (!hits.length) return;',
'    any = true;',
'    var grp = document.createElement("li");',
'    grp.className = "grp";',
'    grp.textContent = lvl.level + " — " + lvl.label;',
'    list.appendChild(grp);',
'    hits.forEach(function(it){',
'      var li = document.createElement("li");',
'      li.className = "opt"; li.setAttribute("role","option");',
'      li.dataset.itemId = it.itemId; li.dataset.locationId = it.locationId;',
'      var code = document.createElement("span"); code.className = "code"; code.textContent = it.code;',
'      var nm = document.createElement("span"); nm.className = "nm";',
'      nm.textContent = it.name; ',
'      var em = document.createElement("em"); em.textContent = it.location; nm.appendChild(em);',
'      var badge = document.createElement("span");',
'      badge.className = "pa-badge pa-badge-" + (it.badge === "other" ? "buy" : it.badge);',
'      badge.textContent = it.badge === "buy" ? "Achat" : it.badge === "other" ? "Non classé"',
'        : (it.badge === "todo" ? (it.pendingCount + " à arbitrer") : "Planificateur");',
'      li.appendChild(code); li.appendChild(nm); li.appendChild(badge);',
'      list.appendChild(li);',
'    });',
'  });',
'  if (!any) { var none = document.createElement("li"); none.className = "none"; none.textContent = "Aucun article ne correspond"; list.appendChild(none); }',
'  list.hidden = false; input.setAttribute("aria-expanded","true"); state.cursor = -1;',
'}',
'function closeList(){ list.hidden = true; input.setAttribute("aria-expanded","false"); state.cursor = -1; }',
'',
'input.addEventListener("input", function(){ renderList(this.value); });',
'input.addEventListener("focus", function(){ renderList(this.value); });',
'$("#pa-artToggle").addEventListener("click", function(){ if (list.hidden){ input.focus(); renderList(""); } else closeList(); });',
'input.addEventListener("keydown", function(e){',
'  var opts = list.querySelectorAll("li.opt");',
'  if (e.key === "ArrowDown" || e.key === "ArrowUp"){',
'    e.preventDefault();',
'    if (list.hidden){ renderList(this.value); opts = list.querySelectorAll("li.opt"); }',
'    if (!opts.length) return;',
'    state.cursor += (e.key === "ArrowDown" ? 1 : -1);',
'    if (state.cursor < 0) state.cursor = opts.length - 1;',
'    if (state.cursor >= opts.length) state.cursor = 0;',
'    Array.prototype.forEach.call(opts, function(li,i){ li.classList.toggle("cursor", i===state.cursor); });',
'    opts[state.cursor].scrollIntoView({block:"nearest"});',
'  } else if (e.key === "Enter"){',
'    if (state.cursor > -1 && opts[state.cursor]) { e.preventDefault(); pick(opts[state.cursor].dataset.itemId, opts[state.cursor].dataset.locationId); }',
'  } else if (e.key === "Escape"){ closeList(); }',
'});',
'list.addEventListener("click", function(e){',
'  var li = e.target.closest("li.opt");',
'  if (li) pick(li.dataset.itemId, li.dataset.locationId);',
'});',
'document.addEventListener("click", function(e){ if (!e.target.closest(".pa-combo")) closeList(); });',
'',
'function pick(itemId, locationId){',
'  var it = state.levelsById[itemId + "|" + locationId];',
'  if (!it) return;',
'  state.current = it;',
'  input.value = it.code + " · " + it.name;',
'  closeList();',
'  $("#pa-blank").hidden = true;',
'  $("#pa-content").hidden = false;',
'  $("#pa-cArt").textContent = it.code + " · " + it.name;',
'  $("#pa-cTempsTerm").textContent = it.tempsTerm !== "" ? it.tempsTerm : "—";',
'  $("#pa-cTempsVac").textContent = it.tempsVac !== "" ? it.tempsVac : "—";',
'  $("#pa-cLoc").textContent = it.location;',
'  $("#pa-splitPanel").hidden = true;',
'  $("#pa-preview").hidden = true;',
'  $("#pa-buyNote").hidden = (it.kind === "make");',
'  $("#pa-buyNote").textContent = it.kind === "buy"',
'    ? "Article acheté : la proposition est un ordre d’achat. La répartition se négocie avec le fournisseur, elle n’est pas traitée par cet écran."',
'    : "Préfixe de code non reconnu : article affiché en consultation seule tant qu’il n’est pas classé (paramètre custscript_planif_level_map).";',
'  $("#pa-pickerHint").textContent = it.kind !== "make" ? (it.kind === "buy" ? "Article acheté — consultation seule" : "Niveau non reconnu — consultation seule")',
'    : (it.pendingCount ? it.pendingCount + " proposition(s) à arbitrer" : "Toutes les propositions sont firmées");',
'  loadOrders();',
'}',
'',
'/* ---------------- F2 / F8 : propositions + composants ---------------- */',
'function loadOrders(){',
'  var it = state.current;',
'  var payload = Object.assign({ itemId: it.itemId, locationId: it.locationId }, planPayload());',
'  return api("listOrders", payload).then(function(res){',
'    state.orders = res.orders || [];',
'    state.components = res.components || [];',
'    state.grandchildComponents = res.grandchildComponents || [];',
'    state.selected = null; state.proposal = null; state.weekFilter = "";',
'    $("#pa-splitPanel").hidden = true; $("#pa-preview").hidden = true;',
'    renderWeekOptions();',
'    renderOrders();',
'    renderComponents(res.currentRunId);',
'    renderGrandchildComponents();',
'    loadJournal();',
'  }).catch(function(err){ toast("Échec du chargement : " + err.message, "error", 9000); });',
'}',
'',
'function originCell(originLabel){',
'  var span = document.createElement("span");',
'  span.className = "pa-pill " + (originLabel === "human" ? "pa-pill-human" : "pa-pill-engine");',
'  span.textContent = originLabel === "human" ? "Planificateur" : "Moteur";',
'  return span;',
'}',
'function textCell(v, cls){ var td = document.createElement("td"); if (cls) td.className = cls; td.textContent = v==null?"":String(v); return td; }',
'',
'/* ---------------- filtre par semaine (F2) ---------------- */',
'/* Affichage uniquement : filtre la liste déjà chargée, aucune donnée ni',
'   règle métier recalculée côté client. */',
'function parseIsoLocal(iso){ var p = String(iso||"").split("-"); return p.length===3 ? new Date(+p[0], +p[1]-1, +p[2]) : null; }',
'function fmtDmy(d){ return ("0"+d.getDate()).slice(-2) + "/" + ("0"+(d.getMonth()+1)).slice(-2); }',
'function getIsoWeekNumber(iso){',
'  var p = iso.split("-").map(Number);',
'  var d = new Date(Date.UTC(p[0], p[1]-1, p[2]));',
'  var dayNum = d.getUTCDay() || 7;',
'  d.setUTCDate(d.getUTCDate() + 4 - dayNum);',
'  var yearStart = new Date(Date.UTC(d.getUTCFullYear(), 0, 1));',
'  return Math.ceil((((d - yearStart) / 86400000) + 1) / 7);',
'}',
'function getWeekStartIso(iso){',
'  var d = parseIsoLocal(iso); if (!d) return "";',
'  var day = d.getDay();',
'  d.setDate(d.getDate() + (day === 0 ? -6 : 1 - day));',
'  return isoOf(d);',
'}',
'function weekMatches(orderStartIso, weekStartIso){',
'  return !weekStartIso || getWeekStartIso(orderStartIso) === weekStartIso;',
'}',
'',
'function renderWeekOptions(){',
'  var sel = $("#pa-weekFilter");',
'  var weeks = {};',
'  state.orders.forEach(function(o){ if (o.startDateIso) weeks[getWeekStartIso(o.startDateIso)] = true; });',
'  var keys = Object.keys(weeks).sort();',
'  sel.innerHTML = "";',
'  var allOpt = document.createElement("option"); allOpt.value = ""; allOpt.textContent = "Toutes les semaines";',
'  sel.appendChild(allOpt);',
'  keys.forEach(function(weekStartIso){',
'    var start = parseIsoLocal(weekStartIso);',
'    var end = new Date(start); end.setDate(end.getDate() + 6);',
'    var opt = document.createElement("option");',
'    opt.value = weekStartIso;',
'    opt.textContent = "S" + getIsoWeekNumber(weekStartIso) + " (" + fmtDmy(start) + " - " + fmtDmy(end) + ")";',
'    sel.appendChild(opt);',
'  });',
'  sel.value = keys.indexOf(state.weekFilter) > -1 ? state.weekFilter : "";',
'  state.weekFilter = sel.value;',
'}',
'$("#pa-weekFilter").addEventListener("change", function(){ state.weekFilter = this.value; renderOrders(); });',
'',
'function renderOrders(){',
'  var body = $("#pa-rows"); body.innerHTML = "";',
'  var visible = [];',
'  state.orders.forEach(function(o, i){ if (weekMatches(o.startDateIso, state.weekFilter)) visible.push(i); });',
'  if (!state.orders.length){',
'    var tr0 = document.createElement("tr");',
'    var td0 = document.createElement("td"); td0.colSpan = 5; td0.className = "pa-empty";',
'    td0.textContent = "Aucune proposition sur l’horizon."; tr0.appendChild(td0); body.appendChild(tr0);',
'    return;',
'  }',
'  if (!visible.length){',
'    var tr1 = document.createElement("tr");',
'    var td1 = document.createElement("td"); td1.colSpan = 5; td1.className = "pa-empty";',
'    td1.textContent = "Aucune proposition sur la semaine sélectionnée."; tr1.appendChild(td1); body.appendChild(tr1);',
'    return;',
'  }',
'  visible.forEach(function(i){',
'    var o = state.orders[i];',
'    var tr = document.createElement("tr");',
'    tr.className = (state.selected === i ? "pa-sel " : "") + (o.originLabel === "human" ? "pa-is-human" : "pa-is-engine");',
'    var tdPick = document.createElement("td");',
'    if (state.current.kind === "make" && !o.firmed){',
'      var radio = document.createElement("input");',
'      radio.type = "radio"; radio.name = "pa-pick"; radio.checked = (state.selected === i);',
'      radio.setAttribute("aria-label", "Sélectionner cette proposition");',
'      radio.addEventListener("change", function(){ selectOrder(i); });',
'      tdPick.appendChild(radio);',
'    }',
'    tr.appendChild(tdPick);',
'    tr.appendChild(textCell(o.quantity, "num mono"));',
'    tr.appendChild(textCell(o.startDateIso, "mono"));',
'    tr.appendChild(textCell(o.endDateIso, "mono"));',
'    var tdOrig = document.createElement("td"); tdOrig.appendChild(originCell(o.originLabel)); tr.appendChild(tdOrig);',
'    body.appendChild(tr);',
'  });',
'}',
'',
'function selectOrder(i){',
'  state.selected = i; state.proposal = null;',
'  var o = state.orders[i];',
'  $("#pa-splitPanel").hidden = false;',
'  $("#pa-preview").hidden = true;',
'  if (o.startDateIso) $("#pa-firstDay").value = o.startDateIso;',
'  renderOrders();',
'}',
'',
'function renderComponents(sourceRunId){',
'  var body = $("#pa-comps"); body.innerHTML = "";',
'  var any = false;',
'  state.components.forEach(function(comp){',
'    comp.orders.forEach(function(o){',
'      any = true;',
'      var tr = document.createElement("tr");',
'      tr.className = o.originLabel === "human" ? "pa-is-human" : "pa-is-engine";',
'      tr.appendChild(textCell(comp.level, "mono"));',
'      tr.appendChild(textCell(comp.componentCode + (comp.dataSource === "fallback-window" ? " (approx.)" : "")));',
'      tr.appendChild(textCell(o.quantity, "num mono"));',
'      tr.appendChild(textCell(o.startDateIso, "mono"));',
'      tr.appendChild(textCell(o.endDateIso, "mono"));',
'      var tdOrig = document.createElement("td"); tdOrig.appendChild(originCell(o.originLabel)); tr.appendChild(tdOrig);',
'      body.appendChild(tr);',
'    });',
'  });',
'  if (!any){',
'    var tr0 = document.createElement("tr");',
'    var td0 = document.createElement("td"); td0.colSpan = 6; td0.className = "pa-empty";',
'    td0.textContent = "Aucun composant fabriqué."; tr0.appendChild(td0); body.appendChild(tr0);',
'  }',
'  $("#pa-compStamp").textContent = sourceRunId',
'    ? "Situation issue du run " + sourceRunId + ". Pour ajuster un composant, sélectionnez-le après le prochain recalcul."',
'    : "Aucun calcul connu.";',
'}',
'',
'function renderGrandchildComponents(){',
'  var body = $("#pa-grandcomps"); body.innerHTML = "";',
'  var any = false;',
'  state.grandchildComponents.forEach(function(group){',
'    group.components.forEach(function(comp){',
'      comp.orders.forEach(function(o){',
'        any = true;',
'        var tr = document.createElement("tr");',
'        tr.className = o.originLabel === "human" ? "pa-is-human" : "pa-is-engine";',
'        tr.appendChild(textCell(comp.level, "mono"));',
'        tr.appendChild(textCell(comp.componentCode + (comp.dataSource === "fallback-window" ? " (approx.)" : "")));',
'        tr.appendChild(textCell(group.parentComponentCode, "mono"));',
'        tr.appendChild(textCell(o.quantity, "num mono"));',
'        tr.appendChild(textCell(o.startDateIso, "mono"));',
'        tr.appendChild(textCell(o.endDateIso, "mono"));',
'        var tdOrig = document.createElement("td"); tdOrig.appendChild(originCell(o.originLabel)); tr.appendChild(tdOrig);',
'        body.appendChild(tr);',
'      });',
'    });',
'  });',
'  if (!any){',
'    var tr0 = document.createElement("tr");',
'    var td0 = document.createElement("td"); td0.colSpan = 7; td0.className = "pa-empty";',
'    td0.textContent = "Aucun composant de composant fabriqué."; tr0.appendChild(td0); body.appendChild(tr0);',
'  }',
'}',
'',
'/* ---------------- F3 : fractionnement ---------------- */',
'function fwdDate(iso, add, skipWe){',
'  var p = iso.split("-"); var d = new Date(+p[0], +p[1]-1, +p[2]); var n = 0;',
'  while (n < add){ d.setDate(d.getDate()+1); if (skipWe && (d.getDay()===0||d.getDay()===6)) continue; n++; }',
'  return isoOf(d);',
'}',
'function isoOf(d){ return d.getFullYear() + "-" + ("0"+(d.getMonth()+1)).slice(-2) + "-" + ("0"+d.getDate()).slice(-2); }',
'function fmtQty(n){ return String(Math.round((+n||0)*1000)/1000); }',
'',
'$("#pa-mode").addEventListener("change", function(){',
'  var m = this.value;',
'  $("#pa-lblQty").textContent = m === "lots" ? "Nombre de lots" : "Quantité / jour";',
'  var auto = (m !== "free");',
'  $("#pa-fQty").hidden = !auto; $("#pa-fWork").hidden = !auto;',
'  $("#pa-btnPreview").textContent = auto ? "Proposer une répartition" : "Repartir de la proposition";',
'  $("#pa-preview").hidden = true;',
'});',
'',
'$("#pa-btnPreview").addEventListener("click", function(){',
'  var o = state.orders[state.selected]; if (!o) return;',
'  var mode = $("#pa-mode").value, first = $("#pa-firstDay").value || o.startDateIso;',
'  if (mode === "free"){',
'    state.proposal = [{ quantity: o.quantity, dateIso: first, release: false }];',
'  } else {',
'    var v = Math.max(0.0001, +$("#pa-qtyDay").value || 1);',
'    var skip = $("#pa-workdays").checked, per, count;',
'    if (mode === "perday"){ per = v; count = Math.ceil(o.quantity / v); }',
'    else { count = Math.max(1, Math.round(v)); per = o.quantity / count; }',
'    state.proposal = []; var rest = o.quantity;',
'    for (var k=0; k<count; k++){ var q = Math.min(per, rest); rest -= q;',
'      state.proposal.push({ quantity: Math.round(q*1000)/1000, dateIso: fwdDate(first, k, skip), release: false }); }',
'  }',
'  $("#pa-preview").hidden = false;',
'  renderLines();',
'});',
'',
'$("#pa-btnAddLine").addEventListener("click", function(){',
'  var last = state.proposal[state.proposal.length-1];',
'  state.proposal.push({ quantity: 0, dateIso: last ? fwdDate(last.dateIso, 1, false) : "", release: false });',
'  renderLines();',
'});',
'',
'/* Anticipation d’affichage uniquement (aucune règle métier côté client,',
'   spec Annexe B.2) - le serveur revalide et calcule l’écart définitif à',
'   l’application. */',
'function dateStatus(iso){',
'  if (!/^\\d{4}-\\d{2}-\\d{2}$/.test(iso||"")) return { cls:"err", txt:"Date requise" };',
'  var p = iso.split("-"); var d = new Date(+p[0], +p[1]-1, +p[2]);',
'  var today = new Date(); today.setHours(0,0,0,0);',
'  if (d < today) return { cls:"warn", txt:"Antérieure à aujourd’hui" };',
'  var horizon = new Date(today); horizon.setDate(horizon.getDate() + (window.PA_HORIZON_DAYS||180));',
'  if (d > horizon) return { cls:"warn", txt:"Hors horizon de planification" };',
'  if (d.getDay()===0) return { cls:"err", txt:"Week-end — dimanche" };',
'  if (d.getDay()===6) return { cls:"err", txt:"Week-end — samedi" };',
'  return { cls:"", txt:"" };',
'}',
'',
'function renderLines(){',
'  var body = $("#pa-lineBody"); body.innerHTML = "";',
'  state.proposal.forEach(function(l, i){',
'    var st = dateStatus(l.dateIso);',
'    var tr = document.createElement("tr");',
'    var tdDate = document.createElement("td");',
'    var dateInput = document.createElement("input");',
'    dateInput.type = "date"; dateInput.className = "mono" + (st.cls==="err"?" bad":"");',
'    dateInput.value = l.dateIso; dateInput.setAttribute("aria-label", "Date de la ligne " + (i+1));',
'    dateInput.addEventListener("input", function(){',
'      state.proposal[i].dateIso = this.value;',
'      var s2 = dateStatus(this.value);',
'      this.classList.toggle("bad", s2.cls === "err");',
'      var obs = tr.querySelector(".pa-obs"); obs.className = "pa-obs " + s2.cls; obs.textContent = s2.txt;',
'      paintTotal();',
'    });',
'    tdDate.appendChild(dateInput); tr.appendChild(tdDate);',
'    tr.appendChild(textCell(state.current ? state.current.name : ""));',
'    var tdQty = document.createElement("td");',
'    var qtyInput = document.createElement("input");',
'    qtyInput.type = "number"; qtyInput.step = "any"; qtyInput.min = "0"; qtyInput.className = "mono";',
'    qtyInput.value = l.quantity; qtyInput.setAttribute("aria-label", "Quantité de la ligne " + (i+1));',
'    qtyInput.addEventListener("input", function(){ state.proposal[i].quantity = +this.value || 0; paintTotal(); });',
'    tdQty.appendChild(qtyInput); tr.appendChild(tdQty);',
'    var tdRelease = document.createElement("td");',
'    var releaseInput = document.createElement("input");',
'    releaseInput.type = "checkbox"; releaseInput.checked = !!l.release;',
'    releaseInput.setAttribute("aria-label", "Lancer (released) la ligne " + (i+1));',
'    releaseInput.addEventListener("change", function(){ state.proposal[i].release = this.checked; });',
'    tdRelease.appendChild(releaseInput); tr.appendChild(tdRelease);',
'    var tdObs = document.createElement("td");',
'    var obsSpan = document.createElement("span"); obsSpan.className = "pa-obs " + st.cls; obsSpan.textContent = st.txt;',
'    tdObs.appendChild(obsSpan); tr.appendChild(tdObs);',
'    var tdDel = document.createElement("td");',
'    if (state.proposal.length > 1){',
'      var del = document.createElement("button"); del.className = "pa-del"; del.textContent = "×";',
'      del.setAttribute("aria-label", "Supprimer la ligne " + (i+1));',
'      del.addEventListener("click", function(){ state.proposal.splice(i,1); renderLines(); });',
'      tdDel.appendChild(del);',
'    }',
'    tr.appendChild(tdDel);',
'    body.appendChild(tr);',
'  });',
'  paintTotal();',
'}',
'',
'function paintTotal(){',
'  var o = state.orders[state.selected];',
'  var sum = state.proposal.reduce(function(a,b){ return a + (+b.quantity||0); }, 0);',
'  var diff = Math.round((sum - o.quantity)*1000)/1000;',
'  var html = state.proposal.length + " ligne(s) · total " + fmtQty(sum) + " / origine " + fmtQty(o.quantity);',
'  var total = $("#pa-total"); total.innerHTML = "";',
'  var span = document.createElement("span"); span.className = "mono"; span.textContent = html; total.appendChild(span);',
'  if (Math.abs(diff) < 0.005){ var ok = document.createElement("span"); ok.className = "pa-ok"; ok.textContent = "✓ identique à la quantité d’origine"; total.appendChild(ok); }',
'  var old = $("#pa-flagZone"); if (old) old.remove();',
'  var oldSun = $("#pa-sundayFlag"); if (oldSun) oldSun.remove();',
'  var flag = "";',
'  if (diff < -0.005) flag = "Répartition inférieure de " + fmtQty(-diff) + ". Le besoin restant sera reproposé par le moteur au prochain recalcul.";',
'  else if (diff > 0.005) flag = "Sur-approvisionnement de " + fmtQty(diff) + ". Validation possible, l’écart sera inscrit au journal.";',
'  if (flag){',
'    var div = document.createElement("div"); div.id = "pa-flagZone";',
'    var inner = document.createElement("div"); inner.className = "pa-flag " + (diff>0?"pa-flag-over":"pa-flag-info");',
'    inner.textContent = flag; div.appendChild(inner); total.insertAdjacentElement("afterend", div);',
'  }',
'  // Exception explicite au principe "aucun blocage" de F3 : une',
'  // quantité planifiée un dimanche empêche la validation (règle métier',
'  // demandée par l\'utilisateur, pas une règle de la spec d\'origine).',
'  var hasSundayQty = state.proposal.some(function(l){',
'    var d = parseIsoLocal(l.dateIso);',
'    return d && d.getDay() === 0 && (+l.quantity || 0) > 0;',
'  });',
'  if (hasSundayQty){',
'    var sunDiv = document.createElement("div"); sunDiv.id = "pa-sundayFlag";',
'    var sunInner = document.createElement("div"); sunInner.className = "pa-flag pa-flag-over";',
'    sunInner.textContent = "Au moins une ligne planifie une quantité un dimanche — validation bloquée tant que la date ou la quantité n\'est pas corrigée.";',
'    sunDiv.appendChild(sunInner);',
'    ($("#pa-flagZone") || total).insertAdjacentElement("afterend", sunDiv);',
'  }',
'  $("#pa-btnApply").disabled = (sum <= 0) || hasSundayQty;',
'}',
'',
'$("#pa-btnCancel").addEventListener("click", function(){ $("#pa-preview").hidden = true; });',
'',
'$("#pa-btnApply").addEventListener("click", function(){',
'  var o = state.orders[state.selected]; if (!o) return;',
'  var lines = state.proposal.filter(function(l){ return (+l.quantity||0) > 0 && l.dateIso; });',
'  if (!lines.length) return;',
'  var btn = $("#pa-btnApply"); btn.disabled = true;',
'  api("applySplit", Object.assign({',
'    originalOrderId: o.id, itemId: state.current.itemId, locationId: state.current.locationId,',
'    lines: lines.map(function(l){ return { dateIso: l.dateIso, quantity: l.quantity, release: !!l.release }; })',
'  }, planPayload())).then(function(res){',
'    btn.disabled = false;',
'    if (res.alreadyApplied){',
'      toast("Cette proposition avait déjà été remplacée — aucune double écriture.", "warning");',
'    } else {',
'      var msg = "Répartition en " + lines.length + " ligne(s) firmée(s).";',
'      if (res.quantityGap > 0.005) msg += " Sur-approvisionnement de " + fmtQty(res.quantityGap) + ".";',
'      else if (res.quantityGap < -0.005) msg += " Couverture partielle, reste " + fmtQty(-res.quantityGap) + ".";',
'      if (res.originalDeleteFailed) msg += " Attention : la proposition d’origine n’a pas pu être supprimée, vérifiez les doublons.";',
'      toast(msg, res.originalDeleteFailed || res.quantityGap > 0.005 ? "warning" : "success", 8000);',
'    }',
'    $("#pa-preview").hidden = true; $("#pa-splitPanel").hidden = true;',
'    loadOrders();',
'    refreshPlanBar();',
'  }).catch(function(err){ btn.disabled = false; toast("Échec de l’application : " + err.message, "error", 9000); });',
'});',
'',
'$("#pa-btnRefresh").addEventListener("click", function(){ refreshPlanBar(); if (state.current) loadOrders(); });',
'',
'/* ---------------- F9 : journal ---------------- */',
'function loadJournal(){',
'  var itemId = state.current ? state.current.itemId : null;',
'  return api("listJournal", { itemId: itemId }).then(function(res){ renderJournal(res.entries || []); })',
'    .catch(function(){ /* non bloquant */ });',
'}',
'function renderJournal(entries){',
'  var body = $("#pa-journal"); body.innerHTML = "";',
'  entries.forEach(function(e){',
'    var tr = document.createElement("tr");',
'    tr.appendChild(textCell(e.timestamp, "mono"));',
'    tr.appendChild(textCell(e.userName));',
'    tr.appendChild(textCell((e.itemCode ? e.itemCode + " — " : "") + e.operation));',
'    body.appendChild(tr);',
'  });',
'  $("#pa-journalEmpty").hidden = entries.length > 0;',
'}',
'',
'loadSupplyPlans().then(refreshPlanBar);',
'})();'
        ].join('\n');
    }

    return { renderPage: renderPage };
});
