/**
 * @NApiVersion 2.1
 * @NModuleScope SameAccount
 *
 * WOTree (suitelet) - renderer HTML/CSS/JS
 * Returns the full markup of the UI (CSS + vanilla JS embedded, no
 * N/ui/serverWidget). Modeled on the BIN_TRANSFER tool's pattern: the
 * Suitelet GET renders this page once; all interaction after that goes
 * through fetch() calls to the same Suitelet's POST JSON action router.
 */
define([], function () {

    var WT_VERSION = '1.0.0';

    // Escapes an object for safe injection inside an inline <script> tag -
    // without this, a Work Order or Item value containing "</script>" could
    // break the generated HTML.
    function safeScriptJson(obj) {
        return JSON.stringify(obj || null)
            .replace(/</g, '\\u003c')
            .replace(/>/g, '\\u003e')
            .replace(/\u2028/g, '\\u2028')
            .replace(/\u2029/g, '\\u2029');
    }

    function renderPage(ctx) {
        // ctx = { suiteletUrl, planningCategories:[{id,text}] }
        var url = ctx.suiteletUrl || '';
        var planningCategoriesJson = safeScriptJson(ctx.planningCategories || []);

        return [
'<!DOCTYPE html>',
'<html lang="fr">',
'<head>',
'<meta charset="UTF-8">',
'<meta name="viewport" content="width=device-width, initial-scale=1">',
'<title>Hiérarchie des Ordres de Fabrication</title>',
'<style>', baseCss(), '</style>',
'</head>',
'<body>',
'  <div class="wt-app">',
'    <header class="wt-header">',
'      <div class="wt-title">',
'        <span class="wt-logo" aria-hidden="true">',
'          <svg viewBox="0 0 40 40" xmlns="http://www.w3.org/2000/svg" fill="none">',
'            <rect x="16" y="4" width="10" height="10" rx="2.2" stroke="currentColor" stroke-width="2.2"/>',
'            <rect x="3" y="26" width="10" height="10" rx="2.2" stroke="currentColor" stroke-width="2.2"/>',
'            <rect x="27" y="26" width="10" height="10" rx="2.2" stroke="currentColor" stroke-width="2.2"/>',
'            <path d="M21 14 V19 M21 19 H8 V26 M21 19 H32 V26" stroke="currentColor" stroke-width="2.2" stroke-linecap="round" stroke-linejoin="round"/>',
'          </svg>',
'        </span>',
'        <span class="wt-title-text">',
'          <span class="wt-eyebrow">Fabrication</span>',
'          <span class="wt-name">Hiérarchie des Ordres de Fabrication</span>',
'        </span>',
'        <span class="wt-version">v' + WT_VERSION + '</span>',
'      </div>',
'      <div class="wt-help">',
'        Ordres de fabrication publiés, regroupés selon leur hiérarchie de sous-ensembles (createdfrom).',
'        Modifiez la date de début directement sur une ligne éligible, puis enregistrez - les',
'        modifications sont appliquées par une tâche en arrière-plan, donc enregistrer de nombreuses',
'        lignes à la fois est toujours sans risque.',
'      </div>',
'    </header>',

'    <section class="wt-card wt-filters">',
'      <div class="wt-row">',
'        <div class="wt-field" style="flex:2">',
'          <label>Article assemblé</label>',
'          <input type="text" id="wt-f-item" class="wt-input" placeholder="Tapez un code ou un nom d’article...">',
'          <div class="wt-hint">Recherche sur le code OU le nom affiché de l’article. Filtre uniquement les ordres racines.</div>',
'        </div>',
'        <div class="wt-field" style="flex:2">',
'          <label>Catégorie de planification</label>',
'          <select id="wt-f-category" class="wt-select" multiple size="5"></select>',
'        </div>',
'        <div class="wt-field">',
'          <label>Date de début - à partir de</label>',
'          <input type="date" id="wt-f-from" class="wt-input">',
'        </div>',
'        <div class="wt-field">',
'          <label>Date de début - jusqu’au</label>',
'          <input type="date" id="wt-f-to" class="wt-input">',
'        </div>',
'      </div>',
'      <div class="wt-actions" style="margin-top:14px; padding-top:0; border-top:none">',
'        <button class="wt-btn-primary" id="wt-search">Rechercher</button>',
'        <button class="wt-btn-ghost" id="wt-clear">Effacer les filtres</button>',
'      </div>',
'    </section>',

'    <section class="wt-card wt-results">',
'      <div class="wt-card-head">',
'        <h3>Ordres de Fabrication</h3>',
'        <span class="wt-hint" id="wt-summary">Chargement...</span>',
'      </div>',
'      <div class="wt-table-wrap">',
'        <table class="wt-table">',
'          <thead>',
'            <tr>',
'              <th class="wt-sortable" data-sort="tranId">Ordre de Fabrication <span class="wt-sort-ind"></span></th>',
'              <th class="wt-sortable" data-sort="assemblyItemText">Article assemblé <span class="wt-sort-ind"></span></th>',
'              <th class="wt-sortable" data-sort="assemblyItemDisplayName">Nom affiché de l’article <span class="wt-sort-ind"></span></th>',
'              <th class="wt-sortable" data-sort="statusText">Statut <span class="wt-sort-ind"></span></th>',
'              <th class="wt-sortable num" data-sort="quantity">Qté <span class="wt-sort-ind"></span></th>',
'              <th class="wt-sortable" data-sort="startDate">Date de début <span class="wt-sort-ind"></span></th>',
'              <th class="wt-sortable" data-sort="endDate">Date de fin <span class="wt-sort-ind"></span></th>',
'            </tr>',
'          </thead>',
'          <tbody id="wt-body"><tr><td colspan="7" class="wt-empty">Chargement...</td></tr></tbody>',
'        </table>',
'      </div>',
'      <div class="wt-actions">',
'        <div class="wt-pagination" id="wt-pagination"></div>',
'        <button class="wt-btn-primary" id="wt-save">Enregistrer les modifications</button>',
'      </div>',
'    </section>',

'    <div id="wt-toast" class="wt-toast"></div>',
'    <div id="wt-diag" class="wt-diag" style="display:none">',
'      <div class="wt-diag-head">',
'        <strong>Diagnostic</strong>',
'        <button class="wt-btn-ghost" id="wt-diag-close">Fermer</button>',
'      </div>',
'      <pre id="wt-diag-body"></pre>',
'    </div>',
'  </div>',

'<script>',
'  window.WT_URL = "' + url + '";',
'  window.WT_PLANNING_CATEGORIES = ' + planningCategoriesJson + ';',
'</script>',
'<script>', baseJs(), '</script>',
'</body>',
'</html>'
        ].join('\n');
    }

    function baseCss() {
        return [
            ':root { --ink:#16212b; --ink-grad-top:#1f2e3c; --accent:#0e7490; --accent-strong:#155e75; --accent-soft:#e3f4f8; --accent-soft-tx:#0c5566; --accent-line:#b6e2ec; --bg:#eceff3; --surface:#ffffff; --surface-2:#f5f7f9; --line:#dce2e9; --line-soft:#eaeef2; --tx:#1b2733; --tx-2:#48586a; --tx-3:#6f7d8c; --ok:#15803d; --ok-bg:#dcf3e4; --warn:#9a4216; --warn-bg:#fbe9d8; --danger:#b42318; --danger-bg:#fbe7e5; --radius:9px; --radius-sm:6px; --font:system-ui,-apple-system,"Segoe UI",Roboto,Helvetica,Arial,sans-serif; --mono:ui-monospace,"SF Mono","Cascadia Code",Consolas,monospace; }',
            '*, *::before, *::after { box-sizing:border-box; }',
            'body { margin:0; font-family:var(--font); background:var(--bg); color:var(--tx); font-size:14px; -webkit-font-smoothing:antialiased; }',
            '.wt-app { max-width:1280px; margin:0 auto; padding:18px; }',
            '.wt-header { display:flex; flex-direction:column; gap:9px; padding:16px 20px; background:var(--ink); background-image:linear-gradient(180deg,var(--ink-grad-top),var(--ink)); color:#fff; border-radius:var(--radius) var(--radius) 0 0; border-bottom:3px solid var(--accent); }',
            '.wt-title { display:flex; align-items:center; gap:13px; }',
            '.wt-logo { display:inline-flex; align-items:center; justify-content:center; width:40px; height:40px; background:#fff; color:var(--accent); border-radius:10px; box-shadow:0 1px 0 rgba(255,255,255,0.2), 0 3px 10px rgba(0,0,0,0.28); flex-shrink:0; }',
            '.wt-logo svg { width:26px; height:26px; display:block; }',
            '.wt-title-text { display:flex; flex-direction:column; gap:1px; line-height:1.15; }',
            '.wt-eyebrow { font-size:10px; font-weight:600; letter-spacing:1.7px; text-transform:uppercase; color:#83d3e2; }',
            '.wt-name { font-size:18px; font-weight:600; letter-spacing:0.2px; }',
            '.wt-version { font-family:var(--mono); font-size:11px; background:rgba(255,255,255,0.12); border:1px solid rgba(255,255,255,0.18); padding:2px 9px; border-radius:7px; letter-spacing:0.5px; margin-left:auto; }',
            '.wt-help { font-size:12.5px; line-height:1.55; color:#aab6c1; max-width:90ch; }',
            '.wt-card { background:var(--surface); border:1px solid var(--line); border-radius:var(--radius); padding:16px; margin-bottom:14px; }',
            '.wt-filters { border-radius:0 0 var(--radius) var(--radius); border-top:none; }',
            '.wt-card-head { display:flex; justify-content:space-between; align-items:center; gap:12px; margin-bottom:12px; }',
            '.wt-card-head h3 { margin:0; font-size:14px; font-weight:600; letter-spacing:0.2px; color:var(--tx); }',
            '.wt-row { display:flex; gap:14px; align-items:flex-start; flex-wrap:wrap; }',
            '.wt-field { display:flex; flex-direction:column; gap:5px; flex:1; min-width:180px; }',
            '.wt-field label { font-size:11px; font-weight:600; color:var(--tx-2); text-transform:uppercase; letter-spacing:0.6px; }',
            '.wt-input, .wt-select { padding:9px 11px; border:1px solid var(--line); border-radius:var(--radius-sm); font-size:14px; font-family:var(--font); color:var(--tx); background:#fff; transition:border-color .12s, box-shadow .12s; }',
            '.wt-input:focus, .wt-select:focus { outline:none; border-color:var(--accent); box-shadow:0 0 0 3px rgba(14,116,144,0.15); }',
            '.wt-hint { font-size:11px; color:var(--tx-3); }',
            '.wt-table-wrap { overflow-x:auto; max-height:65vh; overflow-y:auto; border:1px solid var(--line-soft); border-radius:var(--radius-sm); }',
            '.wt-table { width:100%; border-collapse:collapse; font-size:13px; }',
            '.wt-table th { position:sticky; top:0; z-index:2; text-align:left; padding:9px 10px; background:var(--surface-2); border-bottom:1px solid var(--line); font-weight:600; font-size:11px; color:var(--tx-2); text-transform:uppercase; letter-spacing:0.5px; }',
            '.wt-table td { padding:7px 10px; border-bottom:1px solid var(--line-soft); vertical-align:middle; white-space:nowrap; }',
            '.wt-table th.num, .wt-table td.num { text-align:right; font-family:var(--mono); font-variant-numeric:tabular-nums; }',
            '.wt-table th.wt-sortable { cursor:pointer; user-select:none; }',
            '.wt-table th.wt-sortable:hover { background:var(--accent-soft); color:var(--accent-strong); }',
            '.wt-table th.wt-sortable.wt-sort-active { background:var(--accent-soft); color:var(--accent-strong); }',
            '.wt-sort-ind { display:inline-block; width:10px; color:var(--tx-3); font-size:10px; margin-left:2px; }',
            '.wt-table th.wt-sort-active .wt-sort-ind { color:var(--accent); font-weight:700; }',
            '.wt-table tbody tr:hover { background:var(--accent-soft); }',
            '.wt-table tbody tr.wt-root-row { background:var(--surface-2); }',
            '.wt-table tbody tr.wt-root-row:hover { background:var(--accent-soft); }',
            '.wt-tree-cell { display:flex; align-items:center; gap:6px; font-family:var(--mono); }',
            '.wt-tree-indent { color:var(--tx-3); white-space:pre; }',
            '.wt-root-badge { font-size:9px; font-weight:700; text-transform:uppercase; letter-spacing:0.4px; background:var(--accent-soft); color:var(--accent-soft-tx); border-radius:20px; padding:1px 7px; margin-left:6px; }',
            '.wt-badge { display:inline-block; padding:2px 9px; border-radius:20px; font-size:11px; font-weight:600; }',
            '.wt-badge-released { background:var(--ok-bg); color:var(--ok); }',
            '.wt-badge-other { background:var(--surface-2); color:var(--tx-2); border:1px solid var(--line); }',
            '.wt-date-input { padding:6px 8px; border:1px solid var(--line); border-radius:6px; font-family:var(--font); font-size:13px; color:var(--tx); background:#fff; }',
            '.wt-date-input:focus { outline:none; border-color:var(--accent); box-shadow:0 0 0 3px rgba(14,116,144,0.15); }',
            '.wt-date-input.wt-changed { border-color:var(--accent); background:var(--accent-soft); font-weight:600; }',
            '.wt-date-input.wt-pending { border-style:dashed; border-color:var(--warn); background:var(--warn-bg); color:var(--warn); cursor:wait; opacity:0.85; }',
            '.wt-date-readonly { color:var(--tx-3); font-family:var(--mono); }',
            '.wt-actions { display:flex; gap:10px; align-items:center; justify-content:space-between; margin-top:14px; padding-top:14px; border-top:1px solid var(--line-soft); flex-wrap:wrap; }',
            '.wt-btn-primary, .wt-btn-ghost { padding:9px 18px; border-radius:var(--radius-sm); font-family:var(--font); font-size:13px; font-weight:600; cursor:pointer; border:1px solid transparent; transition:background .14s, border-color .14s, color .14s; }',
            '.wt-btn-primary { background:var(--accent); color:#fff; }',
            '.wt-btn-primary:hover { background:var(--accent-strong); }',
            '.wt-btn-primary:disabled { background:#9fb0b8; cursor:not-allowed; }',
            '.wt-btn-ghost { background:transparent; border-color:var(--line); color:var(--tx-2); }',
            '.wt-btn-ghost:hover { background:var(--surface-2); border-color:#c3ccd6; }',
            '.wt-pagination { display:flex; gap:8px; align-items:center; font-size:12px; color:var(--tx-2); }',
            '.wt-pagination button { padding:6px 12px; border-radius:6px; border:1px solid var(--line); background:#fff; cursor:pointer; font-size:12px; font-weight:600; color:var(--tx-2); }',
            '.wt-pagination button:hover:not(:disabled) { background:var(--surface-2); border-color:#c3ccd6; }',
            '.wt-pagination button:disabled { opacity:0.4; cursor:not-allowed; }',
            '.wt-empty { text-align:center; color:var(--tx-3); padding:22px; font-style:italic; }',
            '.wt-toast { position:fixed; bottom:22px; right:22px; background:var(--ink); color:#fff; padding:12px 16px; border-radius:9px; opacity:0; transform:translateY(6px); pointer-events:none; transition:opacity .2s, transform .2s; z-index:9999; max-width:420px; font-size:13px; box-shadow:0 10px 28px rgba(0,0,0,0.24); border-left:3px solid var(--accent); }',
            '.wt-toast.show { opacity:1; transform:translateY(0); pointer-events:auto; }',
            '.wt-toast.error { background:var(--danger); border-left-color:#7f1d1d; }',
            '.wt-toast.success { background:var(--ok); border-left-color:#0f5c2e; }',
            '.wt-toast.warning { background:var(--warn); border-left-color:#7c3a06; }',
            '.wt-diag { position:fixed; bottom:20px; left:20px; right:20px; max-width:900px; margin:auto; background:var(--ink); color:#cdd7df; border:1px solid #2a3947; border-radius:11px; padding:14px; max-height:50vh; overflow:hidden; box-shadow:0 14px 36px rgba(0,0,0,0.38); z-index:9998; font-size:11px; }',
            '.wt-diag-head { display:flex; justify-content:space-between; align-items:center; margin-bottom:8px; }',
            '.wt-diag-head .wt-btn-ghost { color:#9fb0bd; border-color:#3a4b59; padding:3px 10px; font-size:11px; }',
            '.wt-diag pre { font-family:var(--mono); font-size:11px; line-height:1.5; max-height:40vh; overflow:auto; margin:0; white-space:pre-wrap; word-break:break-word; }',
            '@media (prefers-reduced-motion: reduce) { *, *::before, *::after { animation-duration:0.01ms !important; transition-duration:0.01ms !important; } }'
        ].join('\n');
    }

    function baseJs() {
        return [
'(function () {',
'  "use strict";',
'',
'  var URL = window.WT_URL || "";',
'  var PLANNING_CATEGORIES = window.WT_PLANNING_CATEGORIES || [];',
'',
'  var state = {',
'    page: 1, totalPages: 1, changes: {}, pendingTasks: [], pollTimer: null,',
'    sortField: null, sortDir: "asc"',
'  };',
'',
'  function $(sel, ctx) { return (ctx || document).querySelector(sel); }',
'',
'  function toast(msg, type, durationMs) {',
'    var el = $("#wt-toast");',
'    el.textContent = msg;',
'    el.className = "wt-toast show " + (type || "");',
'    setTimeout(function () { el.className = "wt-toast"; }, durationMs || 6000);',
'  }',
'',
'  function showDiag(text) {',
'    $("#wt-diag-body").textContent = text;',
'    $("#wt-diag").style.display = "block";',
'  }',
'  $("#wt-diag-close").addEventListener("click", function () { $("#wt-diag").style.display = "none"; });',
'',
'  function api(action, payload) {',
'    return fetch(URL, {',
'      method: "POST",',
'      headers: { "Content-Type": "application/json" },',
'      body: JSON.stringify({ action: action, payload: payload || {} })',
'    }).then(function (r) {',
'      return r.text().then(function (txt) {',
'        var j = null;',
'        try { j = txt ? JSON.parse(txt) : {}; }',
'        catch (parseErr) {',
'          var preview = (txt || "(vide)").replace(/\\s+/g, " ").substring(0, 300);',
'          throw new Error("Réponse non-JSON (HTTP " + r.status + ") : " + preview);',
'        }',
'        if (!r.ok || j.error) {',
'          throw new Error(j.error || ("HTTP " + r.status));',
'        }',
'        return j;',
'      });',
'    });',
'  }',
'',
'  function fillSelect(selectEl, items) {',
'    items.forEach(function (item) {',
'      var opt = document.createElement("option");',
'      opt.value = item.id;',
'      opt.textContent = item.text;',
'      selectEl.appendChild(opt);',
'    });',
'  }',
'  fillSelect($("#wt-f-category"), PLANNING_CATEGORIES);',
'',
'  function selectedValues(selectEl) {',
'    return Array.prototype.slice.call(selectEl.selectedOptions).map(function (o) { return o.value; });',
'  }',
'',
'  function currentFilters() {',
'    return {',
'      itemSearchText: $("#wt-f-item").value.trim(),',
'      planningCategoryIds: selectedValues($("#wt-f-category")),',
'      startDateFrom: $("#wt-f-from").value || "",',
'      startDateTo: $("#wt-f-to").value || "",',
'      sortField: state.sortField,',
'      sortDir: state.sortDir',
'    };',
'  }',
'',
'  function updateSortIndicators() {',
'    Array.prototype.slice.call(document.querySelectorAll(".wt-sortable")).forEach(function (th) {',
'      var active = th.dataset.sort === state.sortField;',
'      th.classList.toggle("wt-sort-active", active);',
'      var ind = th.querySelector(".wt-sort-ind");',
'      ind.textContent = active ? (state.sortDir === "desc" ? "\\u25bc" : "\\u25b2") : "";',
'    });',
'  }',
'',
'  Array.prototype.slice.call(document.querySelectorAll(".wt-sortable")).forEach(function (th) {',
'    th.addEventListener("click", function () {',
'      var field = th.dataset.sort;',
'      if (state.sortField === field) {',
'        state.sortDir = state.sortDir === "asc" ? "desc" : "asc";',
'      } else {',
'        state.sortField = field;',
'        state.sortDir = "asc";',
'      }',
'      updateSortIndicators();',
'      loadTree(1);',
'    });',
'  });',
'',
'  function loadTree(page) {',
'    var body = $("#wt-body");',
'    body.innerHTML = "";',
'    var trLoading = document.createElement("tr");',
'    var tdLoading = document.createElement("td");',
'    tdLoading.colSpan = 7;',
'    tdLoading.className = "wt-empty";',
'    tdLoading.textContent = "Chargement...";',
'    trLoading.appendChild(tdLoading);',
'    body.appendChild(trLoading);',
'',
'    var payload = currentFilters();',
'    payload.page = page || 1;',
'',
'    return api("loadTree", payload).then(function (res) {',
'      state.page = res.currentPage;',
'      state.totalPages = res.totalRootPages;',
'      state.changes = {};',
'      renderRows(res.rows);',
'      renderPagination(res.currentPage, res.totalRootPages);',
'      $("#wt-summary").textContent = res.totalRootCount + " ordre(s) de fabrication racine(s) trouvé(s) - page " +',
'        res.currentPage + " sur " + res.totalRootPages;',
'    }).catch(function (err) {',
'      body.innerHTML = "";',
'      var tr = document.createElement("tr");',
'      var td = document.createElement("td");',
'      td.colSpan = 7;',
'      td.className = "wt-empty";',
'      td.textContent = "Échec du chargement.";',
'      tr.appendChild(td);',
'      body.appendChild(tr);',
'      toast("Échec du chargement : " + err.message, "error", 9000);',
'      showDiag(String(err.message || err));',
'    });',
'  }',
'',
'  function renderRows(rows) {',
'    var body = $("#wt-body");',
'    body.innerHTML = "";',
'    if (!rows.length) {',
'      var tr0 = document.createElement("tr");',
'      var td0 = document.createElement("td");',
'      td0.colSpan = 7;',
'      td0.className = "wt-empty";',
'      td0.textContent = "Aucun ordre de fabrication ne correspond aux filtres actuels.";',
'      tr0.appendChild(td0);',
'      body.appendChild(tr0);',
'      return;',
'    }',
'    var frag = document.createDocumentFragment();',
'    rows.forEach(function (row) {',
'      var tr = document.createElement("tr");',
'      if (row.isRoot) tr.className = "wt-root-row";',
'',
'      var tdTree = document.createElement("td");',
'      var wrap = document.createElement("div");',
'      wrap.className = "wt-tree-cell";',
'      if (row.depth > 0) {',
'        var indent = document.createElement("span");',
'        indent.className = "wt-tree-indent";',
'        indent.textContent = "  ".repeat(row.depth - 1) + "\\u2514\\u2500 ";',
'        wrap.appendChild(indent);',
'      }',
'      var label = document.createElement("span");',
'      label.textContent = row.tranId;',
'      wrap.appendChild(label);',
'      if (row.isRoot) {',
'        var badge = document.createElement("span");',
'        badge.className = "wt-root-badge";',
'        badge.textContent = "Racine";',
'        wrap.appendChild(badge);',
'      }',
'      tdTree.appendChild(wrap);',
'      tr.appendChild(tdTree);',
'',
'      tr.appendChild(textCell(row.assemblyItemText));',
'      tr.appendChild(textCell(row.assemblyItemDisplayName));',
'',
'      var tdStatus = document.createElement("td");',
'      var statusBadge = document.createElement("span");',
'      statusBadge.className = "wt-badge " + (row.editable ? "wt-badge-released" : "wt-badge-other");',
'      statusBadge.textContent = row.statusText;',
'      tdStatus.appendChild(statusBadge);',
'      tr.appendChild(tdStatus);',
'',
'      tr.appendChild(textCell(row.quantity, "num"));',
'',
'      var tdStart = document.createElement("td");',
'      if (row.editable) {',
'        var input = document.createElement("input");',
'        input.type = "date";',
'        input.className = "wt-date-input";',
'        input.value = row.startDateIso || "";',
'        input.dataset.id = row.id;',
'        input.dataset.orig = row.startDateIso || "";',
'        input.addEventListener("change", function () {',
'          if (input.value && input.value !== input.dataset.orig) {',
'            state.changes[row.id] = input.value;',
'            input.classList.add("wt-changed");',
'          } else {',
'            delete state.changes[row.id];',
'            input.classList.remove("wt-changed");',
'          }',
'        });',
'        tdStart.appendChild(input);',
'      } else {',
'        var span = document.createElement("span");',
'        span.className = "wt-date-readonly";',
'        span.textContent = row.startDate || "";',
'        tdStart.appendChild(span);',
'      }',
'      tr.appendChild(tdStart);',
'',
'      tr.appendChild(textCell(row.endDate));',
'',
'      frag.appendChild(tr);',
'    });',
'    body.appendChild(frag);',
'  }',
'',
'  function textCell(value, extraClass) {',
'    var td = document.createElement("td");',
'    if (extraClass) td.className = extraClass;',
'    td.textContent = value || "";',
'    return td;',
'  }',
'',
'  function renderPagination(page, totalPages) {',
'    var el = $("#wt-pagination");',
'    el.innerHTML = "";',
'    var prev = document.createElement("button");',
'    prev.textContent = "\\u2190 Précédent";',
'    prev.disabled = page <= 1;',
'    prev.addEventListener("click", function () { loadTree(page - 1); });',
'    var label = document.createElement("span");',
'    label.textContent = "Page " + page + " sur " + totalPages;',
'    var next = document.createElement("button");',
'    next.textContent = "Suivant \\u2192";',
'    next.disabled = page >= totalPages;',
'    next.addEventListener("click", function () { loadTree(page + 1); });',
'    el.appendChild(prev);',
'    el.appendChild(label);',
'    el.appendChild(next);',
'  }',
'',
'  $("#wt-search").addEventListener("click", function () { loadTree(1); });',
'  $("#wt-f-item").addEventListener("keydown", function (e) { if (e.key === "Enter") loadTree(1); });',
'  $("#wt-clear").addEventListener("click", function () {',
'    $("#wt-f-item").value = "";',
'    $("#wt-f-category").selectedIndex = -1;',
'    $("#wt-f-from").value = "";',
'    $("#wt-f-to").value = "";',
'    loadTree(1);',
'  });',
'',
'  // Saving is asynchronous (a queued Map/Reduce job, never applied',
'  // synchronously) - reloading the tree right after Save would still show',
'  // the pre-change record and look like the edit reverted. Instead: mark',
'  // the saved inputs as pending, poll the job status, and only',
'  // reload once it has actually finished.',
'  function markPending(ids) {',
'    ids.forEach(function (id) {',
'      var input = document.querySelector(\'.wt-date-input[data-id="\' + id + \'"]\');',
'      if (input) {',
'        input.disabled = true;',
'        input.classList.remove("wt-changed");',
'        input.classList.add("wt-pending");',
'        input.title = "Enregistrement en arrière-plan...";',
'      }',
'    });',
'  }',
'',
'  function schedulePoll() {',
'    if (state.pollTimer) return;',
'    state.pollTimer = setInterval(pollAllPending, 4000);',
'  }',
'',
'  function pollAllPending() {',
'    if (!state.pendingTasks.length) {',
'      clearInterval(state.pollTimer);',
'      state.pollTimer = null;',
'      return;',
'    }',
'    state.pendingTasks.slice().forEach(function (job) {',
'      job.attempts++;',
'      api("checkStatus", { taskId: job.taskId, stagingFileId: job.stagingFileId }).then(function (res) {',
'        var done = res.status === "COMPLETE" || res.status === "FAILED";',
'        var giveUp = !done && job.attempts > 30;',
'        if (!done && !giveUp) return;',
'',
'        state.pendingTasks = state.pendingTasks.filter(function (j) { return j !== job; });',
'',
'        if (giveUp) {',
'          toast("Toujours en cours de traitement en arrière-plan - actualisez plus tard pour voir le résultat.", "warning", 9000);',
'        } else if (res.status === "COMPLETE") {',
'          var succeeded = res.succeeded || 0;',
'          var failed = res.failed || 0;',
'          var msg = succeeded + " modification(s) appliquée(s)" + (failed ? ", " + failed + " échec(s)" : "") + ".";',
'          toast(msg, failed ? "warning" : "success", 8000);',
'          if (failed && res.errors && res.errors.length) showDiag(JSON.stringify(res.errors, null, 2));',
'        } else {',
'          toast("La tâche en arrière-plan a échoué à appliquer les modifications.", "error", 9000);',
'        }',
'        loadTree(state.page);',
'      }).catch(function () { /* transient poll error - retry next tick */ });',
'    });',
'  }',
'',
'  $("#wt-save").addEventListener("click", function () {',
'    var ids = Object.keys(state.changes);',
'    if (!ids.length) {',
'      toast("Aucune modification de date de début à enregistrer.", "warning");',
'      return;',
'    }',
'    if (!window.confirm("Enregistrer " + ids.length + " modification(s) de date de début ? Cela déclenche une tâche en arrière-plan.")) {',
'      return;',
'    }',
'    var changes = ids.map(function (id) { return { id: id, startdate: state.changes[id] }; });',
'    var btn = $("#wt-save");',
'    btn.disabled = true;',
'    api("save", { changes: changes }).then(function (res) {',
'      btn.disabled = false;',
'      state.changes = {};',
'      if (res.taskId) {',
'        markPending(ids);',
'        state.pendingTasks.push({ taskId: res.taskId, stagingFileId: res.stagingFileId, attempts: 0 });',
'        schedulePoll();',
'        toast(res.queued + " modification(s) mise(s) en file d’attente - application en arrière-plan..." +',
'          (res.dropped ? " " + res.dropped + " ligne(s) ignorée(s) (statut modifié depuis)." : ""), "warning", 6000);',
'      } else {',
'        toast("Aucune modification valide n’a été enregistrée." + (res.dropped ? " " + res.dropped + " ligne(s) ignorée(s)." : ""), "warning");',
'      }',
'    }).catch(function (err) {',
'      btn.disabled = false;',
'      toast("Échec de l’enregistrement : " + err.message, "error", 9000);',
'      showDiag(String(err.message || err));',
'    });',
'  });',
'',
'  loadTree(1);',
'})();'
        ].join('\n');
    }

    return { renderPage: renderPage };
});
