/**
 * @NApiVersion 2.1
 * @NModuleScope SameAccount
 *
 * WOTree (suitelet) - renderer HTML/CSS/JS
 * Returns the full markup of the UI (CSS + vanilla JS embedded, no
 * N/ui/serverWidget). Modeled on the BIN_TRANSFER tool's pattern: the
 * Suitelet GET renders this page once; all interaction after that goes
 * through fetch() calls to the same Suitelet's POST JSON action router.
 */
define([], function () {

    var WT_VERSION = '1.0.0';

    // Escapes an object for safe injection inside an inline <script> tag -
    // without this, a Work Order or Item value containing "</script>" could
    // break the generated HTML.
    function safeScriptJson(obj) {
        return JSON.stringify(obj || null)
            .replace(/</g, '\\u003c')
            .replace(/>/g, '\\u003e')
            .replace(/\u2028/g, '\\u2028')
            .replace(/\u2029/g, '\\u2029');
    }

    function renderPage(ctx) {
        // ctx = { suiteletUrl, assemblyItems:[{id,text}], planningCategories:[{id,text}] }
        var url = ctx.suiteletUrl || '';
        var assemblyItemsJson = safeScriptJson(ctx.assemblyItems || []);
        var planningCategoriesJson = safeScriptJson(ctx.planningCategories || []);

        return [
'<!DOCTYPE html>',
'<html lang="en">',
'<head>',
'<meta charset="UTF-8">',
'<meta name="viewport" content="width=device-width, initial-scale=1">',
'<title>Work Order Hierarchy</title>',
'<style>', baseCss(), '</style>',
'</head>',
'<body>',
'  <div class="wt-app">',
'    <header class="wt-header">',
'      <div class="wt-title">',
'        <span class="wt-logo" aria-hidden="true">',
'          <svg viewBox="0 0 40 40" xmlns="http://www.w3.org/2000/svg" fill="none">',
'            <rect x="16" y="4" width="10" height="10" rx="2.2" stroke="currentColor" stroke-width="2.2"/>',
'            <rect x="3" y="26" width="10" height="10" rx="2.2" stroke="currentColor" stroke-width="2.2"/>',
'            <rect x="27" y="26" width="10" height="10" rx="2.2" stroke="currentColor" stroke-width="2.2"/>',
'            <path d="M21 14 V19 M21 19 H8 V26 M21 19 H32 V26" stroke="currentColor" stroke-width="2.2" stroke-linecap="round" stroke-linejoin="round"/>',
'          </svg>',
'        </span>',
'        <span class="wt-title-text">',
'          <span class="wt-eyebrow">Manufacturing</span>',
'          <span class="wt-name">Work Order Hierarchy</span>',
'        </span>',
'        <span class="wt-version">v' + WT_VERSION + '</span>',
'      </div>',
'      <div class="wt-help">',
'        Released Work Orders grouped by their sub-assembly hierarchy (createdfrom).',
'        Edit the Start Date on any Released row inline, then Save - changes are',
'        applied by a background job so saving many rows at once is always safe.',
'      </div>',
'    </header>',

'    <section class="wt-card wt-filters">',
'      <div class="wt-row">',
'        <div class="wt-field" style="flex:2">',
'          <label>Assembly Item</label>',
'          <select id="wt-f-item" class="wt-select" multiple size="5"></select>',
'          <div class="wt-hint">Ctrl/Cmd-click to select multiple. Filters root Work Orders only.</div>',
'        </div>',
'        <div class="wt-field" style="flex:2">',
'          <label>Planning Item Category</label>',
'          <select id="wt-f-category" class="wt-select" multiple size="5"></select>',
'        </div>',
'        <div class="wt-field">',
'          <label>Start Date From</label>',
'          <input type="date" id="wt-f-from" class="wt-input">',
'        </div>',
'        <div class="wt-field">',
'          <label>Start Date To</label>',
'          <input type="date" id="wt-f-to" class="wt-input">',
'        </div>',
'      </div>',
'      <div class="wt-actions" style="margin-top:14px; padding-top:0; border-top:none">',
'        <button class="wt-btn-primary" id="wt-search">Search</button>',
'        <button class="wt-btn-ghost" id="wt-clear">Clear filters</button>',
'      </div>',
'    </section>',

'    <section class="wt-card wt-results">',
'      <div class="wt-card-head">',
'        <h3>Work Orders</h3>',
'        <span class="wt-hint" id="wt-summary">Loading...</span>',
'      </div>',
'      <div class="wt-table-wrap">',
'        <table class="wt-table">',
'          <thead>',
'            <tr>',
'              <th>Work Order</th>',
'              <th>Assembly Item</th>',
'              <th>Status</th>',
'              <th class="num">Qty</th>',
'              <th>End Date</th>',
'              <th>Start Date</th>',
'            </tr>',
'          </thead>',
'          <tbody id="wt-body"><tr><td colspan="6" class="wt-empty">Loading...</td></tr></tbody>',
'        </table>',
'      </div>',
'      <div class="wt-actions">',
'        <div class="wt-pagination" id="wt-pagination"></div>',
'        <button class="wt-btn-primary" id="wt-save">Save Changes</button>',
'      </div>',
'    </section>',

'    <div id="wt-toast" class="wt-toast"></div>',
'    <div id="wt-diag" class="wt-diag" style="display:none">',
'      <div class="wt-diag-head">',
'        <strong>Diagnostic</strong>',
'        <button class="wt-btn-ghost" id="wt-diag-close">Close</button>',
'      </div>',
'      <pre id="wt-diag-body"></pre>',
'    </div>',
'  </div>',

'<script>',
'  window.WT_URL = "' + url + '";',
'  window.WT_ASSEMBLY_ITEMS = ' + assemblyItemsJson + ';',
'  window.WT_PLANNING_CATEGORIES = ' + planningCategoriesJson + ';',
'</script>',
'<script>', baseJs(), '</script>',
'</body>',
'</html>'
        ].join('\n');
    }

    function baseCss() {
        return [
            ':root { --ink:#16212b; --ink-grad-top:#1f2e3c; --accent:#0e7490; --accent-strong:#155e75; --accent-soft:#e3f4f8; --accent-soft-tx:#0c5566; --accent-line:#b6e2ec; --bg:#eceff3; --surface:#ffffff; --surface-2:#f5f7f9; --line:#dce2e9; --line-soft:#eaeef2; --tx:#1b2733; --tx-2:#48586a; --tx-3:#6f7d8c; --ok:#15803d; --ok-bg:#dcf3e4; --warn:#9a4216; --warn-bg:#fbe9d8; --danger:#b42318; --danger-bg:#fbe7e5; --radius:9px; --radius-sm:6px; --font:system-ui,-apple-system,"Segoe UI",Roboto,Helvetica,Arial,sans-serif; --mono:ui-monospace,"SF Mono","Cascadia Code",Consolas,monospace; }',
            '*, *::before, *::after { box-sizing:border-box; }',
            'body { margin:0; font-family:var(--font); background:var(--bg); color:var(--tx); font-size:14px; -webkit-font-smoothing:antialiased; }',
            '.wt-app { max-width:1280px; margin:0 auto; padding:18px; }',
            '.wt-header { display:flex; flex-direction:column; gap:9px; padding:16px 20px; background:var(--ink); background-image:linear-gradient(180deg,var(--ink-grad-top),var(--ink)); color:#fff; border-radius:var(--radius) var(--radius) 0 0; border-bottom:3px solid var(--accent); }',
            '.wt-title { display:flex; align-items:center; gap:13px; }',
            '.wt-logo { display:inline-flex; align-items:center; justify-content:center; width:40px; height:40px; background:#fff; color:var(--accent); border-radius:10px; box-shadow:0 1px 0 rgba(255,255,255,0.2), 0 3px 10px rgba(0,0,0,0.28); flex-shrink:0; }',
            '.wt-logo svg { width:26px; height:26px; display:block; }',
            '.wt-title-text { display:flex; flex-direction:column; gap:1px; line-height:1.15; }',
            '.wt-eyebrow { font-size:10px; font-weight:600; letter-spacing:1.7px; text-transform:uppercase; color:#83d3e2; }',
            '.wt-name { font-size:18px; font-weight:600; letter-spacing:0.2px; }',
            '.wt-version { font-family:var(--mono); font-size:11px; background:rgba(255,255,255,0.12); border:1px solid rgba(255,255,255,0.18); padding:2px 9px; border-radius:7px; letter-spacing:0.5px; margin-left:auto; }',
            '.wt-help { font-size:12.5px; line-height:1.55; color:#aab6c1; max-width:90ch; }',
            '.wt-card { background:var(--surface); border:1px solid var(--line); border-radius:var(--radius); padding:16px; margin-bottom:14px; }',
            '.wt-filters { border-radius:0 0 var(--radius) var(--radius); border-top:none; }',
            '.wt-card-head { display:flex; justify-content:space-between; align-items:center; gap:12px; margin-bottom:12px; }',
            '.wt-card-head h3 { margin:0; font-size:14px; font-weight:600; letter-spacing:0.2px; color:var(--tx); }',
            '.wt-row { display:flex; gap:14px; align-items:flex-start; flex-wrap:wrap; }',
            '.wt-field { display:flex; flex-direction:column; gap:5px; flex:1; min-width:180px; }',
            '.wt-field label { font-size:11px; font-weight:600; color:var(--tx-2); text-transform:uppercase; letter-spacing:0.6px; }',
            '.wt-input, .wt-select { padding:9px 11px; border:1px solid var(--line); border-radius:var(--radius-sm); font-size:14px; font-family:var(--font); color:var(--tx); background:#fff; transition:border-color .12s, box-shadow .12s; }',
            '.wt-input:focus, .wt-select:focus { outline:none; border-color:var(--accent); box-shadow:0 0 0 3px rgba(14,116,144,0.15); }',
            '.wt-hint { font-size:11px; color:var(--tx-3); }',
            '.wt-table-wrap { overflow-x:auto; max-height:65vh; overflow-y:auto; border:1px solid var(--line-soft); border-radius:var(--radius-sm); }',
            '.wt-table { width:100%; border-collapse:collapse; font-size:13px; }',
            '.wt-table th { position:sticky; top:0; z-index:2; text-align:left; padding:9px 10px; background:var(--surface-2); border-bottom:1px solid var(--line); font-weight:600; font-size:11px; color:var(--tx-2); text-transform:uppercase; letter-spacing:0.5px; }',
            '.wt-table td { padding:7px 10px; border-bottom:1px solid var(--line-soft); vertical-align:middle; white-space:nowrap; }',
            '.wt-table th.num, .wt-table td.num { text-align:right; font-family:var(--mono); font-variant-numeric:tabular-nums; }',
            '.wt-table tbody tr:hover { background:var(--accent-soft); }',
            '.wt-table tbody tr.wt-root-row { background:var(--surface-2); }',
            '.wt-table tbody tr.wt-root-row:hover { background:var(--accent-soft); }',
            '.wt-tree-cell { display:flex; align-items:center; gap:6px; font-family:var(--mono); }',
            '.wt-tree-indent { color:var(--tx-3); white-space:pre; }',
            '.wt-root-badge { font-size:9px; font-weight:700; text-transform:uppercase; letter-spacing:0.4px; background:var(--accent-soft); color:var(--accent-soft-tx); border-radius:20px; padding:1px 7px; margin-left:6px; }',
            '.wt-badge { display:inline-block; padding:2px 9px; border-radius:20px; font-size:11px; font-weight:600; }',
            '.wt-badge-released { background:var(--ok-bg); color:var(--ok); }',
            '.wt-badge-other { background:var(--surface-2); color:var(--tx-2); border:1px solid var(--line); }',
            '.wt-date-input { padding:6px 8px; border:1px solid var(--line); border-radius:6px; font-family:var(--font); font-size:13px; color:var(--tx); background:#fff; }',
            '.wt-date-input:focus { outline:none; border-color:var(--accent); box-shadow:0 0 0 3px rgba(14,116,144,0.15); }',
            '.wt-date-input.wt-changed { border-color:var(--accent); background:var(--accent-soft); font-weight:600; }',
            '.wt-date-readonly { color:var(--tx-3); font-family:var(--mono); }',
            '.wt-actions { display:flex; gap:10px; align-items:center; justify-content:space-between; margin-top:14px; padding-top:14px; border-top:1px solid var(--line-soft); flex-wrap:wrap; }',
            '.wt-btn-primary, .wt-btn-ghost { padding:9px 18px; border-radius:var(--radius-sm); font-family:var(--font); font-size:13px; font-weight:600; cursor:pointer; border:1px solid transparent; transition:background .14s, border-color .14s, color .14s; }',
            '.wt-btn-primary { background:var(--accent); color:#fff; }',
            '.wt-btn-primary:hover { background:var(--accent-strong); }',
            '.wt-btn-primary:disabled { background:#9fb0b8; cursor:not-allowed; }',
            '.wt-btn-ghost { background:transparent; border-color:var(--line); color:var(--tx-2); }',
            '.wt-btn-ghost:hover { background:var(--surface-2); border-color:#c3ccd6; }',
            '.wt-pagination { display:flex; gap:8px; align-items:center; font-size:12px; color:var(--tx-2); }',
            '.wt-pagination button { padding:6px 12px; border-radius:6px; border:1px solid var(--line); background:#fff; cursor:pointer; font-size:12px; font-weight:600; color:var(--tx-2); }',
            '.wt-pagination button:hover:not(:disabled) { background:var(--surface-2); border-color:#c3ccd6; }',
            '.wt-pagination button:disabled { opacity:0.4; cursor:not-allowed; }',
            '.wt-empty { text-align:center; color:var(--tx-3); padding:22px; font-style:italic; }',
            '.wt-toast { position:fixed; bottom:22px; right:22px; background:var(--ink); color:#fff; padding:12px 16px; border-radius:9px; opacity:0; transform:translateY(6px); pointer-events:none; transition:opacity .2s, transform .2s; z-index:9999; max-width:420px; font-size:13px; box-shadow:0 10px 28px rgba(0,0,0,0.24); border-left:3px solid var(--accent); }',
            '.wt-toast.show { opacity:1; transform:translateY(0); pointer-events:auto; }',
            '.wt-toast.error { background:var(--danger); border-left-color:#7f1d1d; }',
            '.wt-toast.success { background:var(--ok); border-left-color:#0f5c2e; }',
            '.wt-toast.warning { background:var(--warn); border-left-color:#7c3a06; }',
            '.wt-diag { position:fixed; bottom:20px; left:20px; right:20px; max-width:900px; margin:auto; background:var(--ink); color:#cdd7df; border:1px solid #2a3947; border-radius:11px; padding:14px; max-height:50vh; overflow:hidden; box-shadow:0 14px 36px rgba(0,0,0,0.38); z-index:9998; font-size:11px; }',
            '.wt-diag-head { display:flex; justify-content:space-between; align-items:center; margin-bottom:8px; }',
            '.wt-diag-head .wt-btn-ghost { color:#9fb0bd; border-color:#3a4b59; padding:3px 10px; font-size:11px; }',
            '.wt-diag pre { font-family:var(--mono); font-size:11px; line-height:1.5; max-height:40vh; overflow:auto; margin:0; white-space:pre-wrap; word-break:break-word; }',
            '@media (prefers-reduced-motion: reduce) { *, *::before, *::after { animation-duration:0.01ms !important; transition-duration:0.01ms !important; } }'
        ].join('\n');
    }

    function baseJs() {
        return [
'(function () {',
'  "use strict";',
'',
'  var URL = window.WT_URL || "";',
'  var ASSEMBLY_ITEMS = window.WT_ASSEMBLY_ITEMS || [];',
'  var PLANNING_CATEGORIES = window.WT_PLANNING_CATEGORIES || [];',
'',
'  var state = { page: 1, totalPages: 1, changes: {} };',
'',
'  function $(sel, ctx) { return (ctx || document).querySelector(sel); }',
'',
'  function toast(msg, type, durationMs) {',
'    var el = $("#wt-toast");',
'    el.textContent = msg;',
'    el.className = "wt-toast show " + (type || "");',
'    setTimeout(function () { el.className = "wt-toast"; }, durationMs || 6000);',
'  }',
'',
'  function showDiag(text) {',
'    $("#wt-diag-body").textContent = text;',
'    $("#wt-diag").style.display = "block";',
'  }',
'  $("#wt-diag-close").addEventListener("click", function () { $("#wt-diag").style.display = "none"; });',
'',
'  function api(action, payload) {',
'    return fetch(URL, {',
'      method: "POST",',
'      headers: { "Content-Type": "application/json" },',
'      body: JSON.stringify({ action: action, payload: payload || {} })',
'    }).then(function (r) {',
'      return r.text().then(function (txt) {',
'        var j = null;',
'        try { j = txt ? JSON.parse(txt) : {}; }',
'        catch (parseErr) {',
'          var preview = (txt || "(empty)").replace(/\\s+/g, " ").substring(0, 300);',
'          throw new Error("Non-JSON response (HTTP " + r.status + "): " + preview);',
'        }',
'        if (!r.ok || j.error) {',
'          throw new Error(j.error || ("HTTP " + r.status));',
'        }',
'        return j;',
'      });',
'    });',
'  }',
'',
'  function fillSelect(selectEl, items) {',
'    items.forEach(function (item) {',
'      var opt = document.createElement("option");',
'      opt.value = item.id;',
'      opt.textContent = item.text;',
'      selectEl.appendChild(opt);',
'    });',
'  }',
'  fillSelect($("#wt-f-item"), ASSEMBLY_ITEMS);',
'  fillSelect($("#wt-f-category"), PLANNING_CATEGORIES);',
'',
'  function selectedValues(selectEl) {',
'    return Array.prototype.slice.call(selectEl.selectedOptions).map(function (o) { return o.value; });',
'  }',
'',
'  function currentFilters() {',
'    return {',
'      assemblyItemIds: selectedValues($("#wt-f-item")),',
'      planningCategoryIds: selectedValues($("#wt-f-category")),',
'      startDateFrom: $("#wt-f-from").value || "",',
'      startDateTo: $("#wt-f-to").value || ""',
'    };',
'  }',
'',
'  function loadTree(page) {',
'    var body = $("#wt-body");',
'    body.innerHTML = "";',
'    var trLoading = document.createElement("tr");',
'    var tdLoading = document.createElement("td");',
'    tdLoading.colSpan = 6;',
'    tdLoading.className = "wt-empty";',
'    tdLoading.textContent = "Loading...";',
'    trLoading.appendChild(tdLoading);',
'    body.appendChild(trLoading);',
'',
'    var payload = currentFilters();',
'    payload.page = page || 1;',
'',
'    return api("loadTree", payload).then(function (res) {',
'      state.page = res.currentPage;',
'      state.totalPages = res.totalRootPages;',
'      state.changes = {};',
'      renderRows(res.rows);',
'      renderPagination(res.currentPage, res.totalRootPages);',
'      $("#wt-summary").textContent = res.totalRootCount + " top-level Work Order(s) match - page " +',
'        res.currentPage + " of " + res.totalRootPages;',
'    }).catch(function (err) {',
'      body.innerHTML = "";',
'      var tr = document.createElement("tr");',
'      var td = document.createElement("td");',
'      td.colSpan = 6;',
'      td.className = "wt-empty";',
'      td.textContent = "Failed to load.";',
'      tr.appendChild(td);',
'      body.appendChild(tr);',
'      toast("Load failed: " + err.message, "error", 9000);',
'      showDiag(String(err.message || err));',
'    });',
'  }',
'',
'  function renderRows(rows) {',
'    var body = $("#wt-body");',
'    body.innerHTML = "";',
'    if (!rows.length) {',
'      var tr0 = document.createElement("tr");',
'      var td0 = document.createElement("td");',
'      td0.colSpan = 6;',
'      td0.className = "wt-empty";',
'      td0.textContent = "No Work Orders match the current filters.";',
'      tr0.appendChild(td0);',
'      body.appendChild(tr0);',
'      return;',
'    }',
'    var frag = document.createDocumentFragment();',
'    rows.forEach(function (row) {',
'      var tr = document.createElement("tr");',
'      if (row.isRoot) tr.className = "wt-root-row";',
'',
'      var tdTree = document.createElement("td");',
'      var wrap = document.createElement("div");',
'      wrap.className = "wt-tree-cell";',
'      if (row.depth > 0) {',
'        var indent = document.createElement("span");',
'        indent.className = "wt-tree-indent";',
'        indent.textContent = "  ".repeat(row.depth - 1) + "\\u2514\\u2500 ";',
'        wrap.appendChild(indent);',
'      }',
'      var label = document.createElement("span");',
'      label.textContent = row.tranId;',
'      wrap.appendChild(label);',
'      if (row.isRoot) {',
'        var badge = document.createElement("span");',
'        badge.className = "wt-root-badge";',
'        badge.textContent = "Root";',
'        wrap.appendChild(badge);',
'      }',
'      tdTree.appendChild(wrap);',
'      tr.appendChild(tdTree);',
'',
'      tr.appendChild(textCell(row.assemblyItemText));',
'',
'      var tdStatus = document.createElement("td");',
'      var statusBadge = document.createElement("span");',
'      statusBadge.className = "wt-badge " + (row.editable ? "wt-badge-released" : "wt-badge-other");',
'      statusBadge.textContent = row.statusText;',
'      tdStatus.appendChild(statusBadge);',
'      tr.appendChild(tdStatus);',
'',
'      tr.appendChild(textCell(row.quantity, "num"));',
'      tr.appendChild(textCell(row.endDate));',
'',
'      var tdStart = document.createElement("td");',
'      if (row.editable) {',
'        var input = document.createElement("input");',
'        input.type = "date";',
'        input.className = "wt-date-input";',
'        input.value = row.startDateIso || "";',
'        input.dataset.id = row.id;',
'        input.dataset.orig = row.startDateIso || "";',
'        input.addEventListener("change", function () {',
'          if (input.value && input.value !== input.dataset.orig) {',
'            state.changes[row.id] = input.value;',
'            input.classList.add("wt-changed");',
'          } else {',
'            delete state.changes[row.id];',
'            input.classList.remove("wt-changed");',
'          }',
'        });',
'        tdStart.appendChild(input);',
'      } else {',
'        var span = document.createElement("span");',
'        span.className = "wt-date-readonly";',
'        span.textContent = row.startDate || "";',
'        tdStart.appendChild(span);',
'      }',
'      tr.appendChild(tdStart);',
'',
'      frag.appendChild(tr);',
'    });',
'    body.appendChild(frag);',
'  }',
'',
'  function textCell(value, extraClass) {',
'    var td = document.createElement("td");',
'    if (extraClass) td.className = extraClass;',
'    td.textContent = value || "";',
'    return td;',
'  }',
'',
'  function renderPagination(page, totalPages) {',
'    var el = $("#wt-pagination");',
'    el.innerHTML = "";',
'    var prev = document.createElement("button");',
'    prev.textContent = "\\u2190 Previous";',
'    prev.disabled = page <= 1;',
'    prev.addEventListener("click", function () { loadTree(page - 1); });',
'    var label = document.createElement("span");',
'    label.textContent = "Page " + page + " of " + totalPages;',
'    var next = document.createElement("button");',
'    next.textContent = "Next \\u2192";',
'    next.disabled = page >= totalPages;',
'    next.addEventListener("click", function () { loadTree(page + 1); });',
'    el.appendChild(prev);',
'    el.appendChild(label);',
'    el.appendChild(next);',
'  }',
'',
'  $("#wt-search").addEventListener("click", function () { loadTree(1); });',
'  $("#wt-clear").addEventListener("click", function () {',
'    $("#wt-f-item").selectedIndex = -1;',
'    $("#wt-f-category").selectedIndex = -1;',
'    $("#wt-f-from").value = "";',
'    $("#wt-f-to").value = "";',
'    loadTree(1);',
'  });',
'',
'  $("#wt-save").addEventListener("click", function () {',
'    var ids = Object.keys(state.changes);',
'    if (!ids.length) {',
'      toast("No start date changes to save.", "warning");',
'      return;',
'    }',
'    if (!window.confirm("Save " + ids.length + " start date change(s)? This queues a background job.")) {',
'      return;',
'    }',
'    var changes = ids.map(function (id) { return { id: id, startdate: state.changes[id] }; });',
'    var btn = $("#wt-save");',
'    btn.disabled = true;',
'    api("save", { changes: changes }).then(function (res) {',
'      btn.disabled = false;',
'      var msg = res.queued + " change(s) queued for background processing" +',
'        (res.taskId ? " (Job ID: " + res.taskId + ")" : "") +',
'        (res.dropped ? ". " + res.dropped + " row(s) skipped (no longer Released)." : ".");',
'      toast(msg, res.queued ? "success" : "warning", 9000);',
'      loadTree(state.page);',
'    }).catch(function (err) {',
'      btn.disabled = false;',
'      toast("Save failed: " + err.message, "error", 9000);',
'      showDiag(String(err.message || err));',
'    });',
'  });',
'',
'  loadTree(1);',
'})();'
        ].join('\n');
    }

    return { renderPage: renderPage };
});
